package module

import (
	"xr-game-server/module/accountcfg"
	"xr-game-server/module/agora"
	"xr-game-server/module/aliyunmoderation"
	"xr-game-server/module/anchorrank"
	"xr-game-server/module/apppkg"
	"xr-game-server/module/auth"
	"xr-game-server/module/banner"
	"xr-game-server/module/botanchor"
	"xr-game-server/module/call"
	"xr-game-server/module/currencylog"
	"xr-game-server/module/customerservice"
	"xr-game-server/module/game"
	"xr-game-server/module/ipgeo"
	"xr-game-server/module/livecfg"
	"xr-game-server/module/liveroom"
	"xr-game-server/module/logquery"
	"xr-game-server/module/message"
	"xr-game-server/module/name"
	"xr-game-server/module/preload"
	"xr-game-server/module/privacypolicy"
	"xr-game-server/module/privateroombilling"
	"xr-game-server/module/randomnick"
	"xr-game-server/module/recharge"
	"xr-game-server/module/resourcemonitor"
	"xr-game-server/module/richrank"
	"xr-game-server/module/shortvideo"
	"xr-game-server/module/stat"
	"xr-game-server/module/ticket"
	"xr-game-server/module/timezon
	"xr-game-server/module/upload"
	"xr-game-server/module/userinfo"
	"xr-game-server/module/verification_code"
	"xr-game-server/module/vip"
	"xr-game-server/module/wallet"
)

func Init() {
	upload.Init()
	randomnick.Init()
	auth.InitAuth()
	preload.Init()
	name.Init()
	currencylog.Init()
	message.Init()
	recharge.Init()
	richrank.Init()
	anchorrank.Init()
	banner.Init()
	ticket.Init()
	privateroombilling.Init()
	vip.Init()
	apppkg.Init()
	game.Init()
	ipgeo.Init()
	agora.Init()
	call.Init()
	livecfg.Init()
	verification_code.Init()
	aliyunmoderation.Init()
	privacypolicy.Init()
	accountcfg.Init()
	customerservice.Init()
	wallet.Init()
	logquery.Init()
	timezonecfg.Init()

	liveroom.Init()
	userinfo.Init()
	botanchor.Init()
	stat.Init()
	resourcemonitor.Init()
	shortvideo.Init()
}
