package entity

// Init 直播相关表迁移与 syndb 注册
func Init() {
	initLiveRoom()
	initLiveRoomCfg()
	initLiveRoomIncome()
	initLiveRoomTag()
	initAnchorSalaryCfg()
	initLiveRevenueShareCfg()
	initLiveRoomGameRecommend()
	initLiveRoomOnline()
	initDailyAnchorEffectiveLive()
	initDailyGuildEffectiveLive()
	initLiveRoomBillingPay()
	initLiveRecord()
	initLiveRecordUser()
	initLiveRevenueLog()
	initAnchorIncomeSettlementLog()
	initGuildIncomeSettlementLog()
	initLiveFollow()
	initLiveTicket()
	initLivePrivateRoomBilling()
	initLiveCfg()
	initLiveGuild()
	initLiveGuildTransferInfo()
	InitLiveGift()
	initHomeBanner()
	initVipCfg()
	initAgoraCfg()
	initAliyunTextModerationCfg()
}
