package errercode

import "xr-game-server/constants/lang"

// codeTextMap 错误码的多语言文案表
// 新增/调整错误码时,需要同步在每个语言映射中维护对应文字
var codeTextMap = map[lang.Lang]map[XRCode]string{
	lang.LangEN: {
		Success:                        "OK",
		EmptyUserId:                    "User id is required",
		EmptyToken:                     "Token is required",
		Token:                          "Invalid or expired token",
		TestEnvClose:                   "Test environment is closed",
		SysError:                       "System error",
		LoginFail:                      "Login failed",
		Ban:                            "Account banned",
		CMSLoginFail:                   "CMS login failed",
		ServerClose:                    "Server is closing, please try later",
		GuildExist:                     "Guild name already exists",
		GuildNonExist:                  "Guild does not exist",
		NoPermission:                   "Permission denied",
		GuildKickSelf:                  "You cannot kick yourself",
		GuildApplyExist:                "Application already exists or state is invalid",
		DiamondAmountInvalid:           "Diamond amount must be positive",
		DiamondNotEnough:               "Insufficient diamond balance",
		GoldAmountInvalid:              "Gold amount must be positive",
		GoldNotEnough:                  "Insufficient gold balance",
		DiamondOverflow:                "Diamond amount overflow",
		GoldOverflow:                   "Gold amount overflow",
		LiveRoomExist:                  "Live room already exists",
		LiveRoomNotAnchor:              "You are not an anchor yet",
		LiveRoomNotExist:               "Live room does not exist",
		LiveRoomBanned:                 "Live room is banned",
		GiftExist:                      "Gift name already exists",
		GiftNonExist:                   "Gift does not exist",
		GiftCountInvalid:               "Invalid gift count",
		GiftOffShelf:                   "Gift is off shelf",
		RechargeCfgExist:               "Recharge config name already exists",
		RechargeCfgNonExist:            "Recharge config does not exist",
		RechargeOrderNonExist:          "Recharge order does not exist",
		RechargeAmountInvalid:          "Recharge amount must be positive",
		RechargeGoldInvalid:            "Recharge gold amount must be positive",
		RechargeOrderStateInvalid:      "Recharge order state does not allow this operation",
		RechargeCfgOffShelf:            "Recharge config is off shelf",
		InvalidParam:                   "Invalid parameter",
		RequestTooFrequent:             "Request too frequent, please try again later",
		DailyLimitExceeded:             "Daily limit exceeded, please try again tomorrow",
		VerifyCodeInvalid:              "Invalid verification code",
		VerifyCodeExpired:              "Verification code expired",
		AccountAlreadyExists:           "Account already exists",
		BannerExist:                    "Banner title already exists",
		BannerNonExist:                 "Banner does not exist",
		UserAlreadyAnchor:              "User is already an anchor",
		ShortVideoExist:                "Short video title already exists",
		ShortVideoNonExist:             "Short video does not exist",
		ShortVideoAlreadyLiked:         "Short video already liked",
		VipCfgExist:                    "VIP level already exists",
		VipCfgNonExist:                 "VIP config does not exist",
		ShortVideoFileTooLarge:         "Short video file exceeds size limit",
		GameCfgExist:                   "Game code already exists",
		GameCfgNonExist:                "Game config does not exist",
		AgoraCfgInvalid:                "Agora config is invalid",
		LiveRoomChatMuted:              "You are muted in this room",
		LiveRoomCannotMuteSelf:         "You cannot mute yourself",
		LiveRoomAudienceNotOnline:      "Audience is not in this room",
		LiveRoomCannotKickSelf:         "You cannot kick yourself",
		LiveRoomKickBanned:             "You were kicked and cannot re-enter this room for 30 minutes",
		TextSensitiveWord:              "Text contains sensitive words",
		AliyunTextModerationCfgInvalid: "Text moderation config is invalid",
		AliyunTextModerationFailed:     "Text moderation service unavailable",
		ImageSensitiveContent:          "Image content is not compliant",
		ImageModerationCfgInvalid:      "Image moderation config is invalid",
		ImageModerationFailed:          "Image moderation service unavailable",
		TicketExist:                    "Ticket name already exists",
		TicketNonExist:                 "Ticket does not exist",
		PrivateRoomBillingNonExist:     "Private room billing config does not exist",
		LiveRoomPrivateAudienceFull:    "Private room audience is full",
		LiveRoomNotLive:                "Live room is not live",
		LiveRoomPaidDanmakuDisabled:    "Paid danmaku is not enabled",
		ShortVideoCategoryExist:        "Short video category name already exists",
		ShortVideoCategoryNonExist:     "Short video category does not exist",
		ShortVideoDailyUploadLimit:     "Daily short video upload limit reached",
	},
	lang.LangZHCN: {
		Success:                        "成功",
		EmptyUserId:                    "用户ID不能为空",
		EmptyToken:                     "Token不能为空",
		Token:                          "Token无效或已过期",
		TestEnvClose:                   "测试环境已关闭",
		SysError:                       "系统错误",
		LoginFail:                      "登录失败",
		Ban:                            "账号已被封禁",
		CMSLoginFail:                   "后台登录失败",
		ServerClose:                    "服务器关闭中,请稍后再试",
		GuildExist:                     "工会名称已存在",
		GuildNonExist:                  "工会不存在",
		NoPermission:                   "没有权限",
		GuildKickSelf:                  "不能剔除自己",
		GuildApplyExist:                "申请已存在或状态不合法",
		DiamondAmountInvalid:           "钻石数量必须为正数",
		DiamondNotEnough:               "钻石余额不足",
		GoldAmountInvalid:              "金币数量必须为正数",
		GoldNotEnough:                  "金币余额不足",
		DiamondOverflow:                "钻石数量溢出",
		GoldOverflow:                   "金币数量溢出",
		LiveRoomExist:                  "直播间已存在",
		LiveRoomNotAnchor:              "您尚未成为主播",
		LiveRoomNotExist:               "直播间不存在",
		LiveRoomBanned:                 "直播间已被封禁",
		GiftExist:                      "礼物名称已存在",
		GiftNonExist:                   "礼物不存在",
		GiftCountInvalid:               "送礼数量不合法",
		GiftOffShelf:                   "礼物已下架",
		RechargeCfgExist:               "充值配置名称已存在",
		RechargeCfgNonExist:            "充值配置不存在",
		RechargeOrderNonExist:          "充值订单不存在",
		RechargeAmountInvalid:          "充值金额必须为正数",
		RechargeGoldInvalid:            "充值发放金币数必须为正数",
		RechargeOrderStateInvalid:      "订单状态不允许此操作",
		RechargeCfgOffShelf:            "充值配置已下架",
		InvalidParam:                   "参数无效",
		RequestTooFrequent:             "请求过于频繁，请稍后再试",
		DailyLimitExceeded:             "超过每日发送限制，请明天再试",
		VerifyCodeInvalid:              "验证码无效",
		VerifyCodeExpired:              "验证码已过期",
		AccountAlreadyExists:           "账号已存在",
		BannerExist:                    "Banner标题已存在",
		BannerNonExist:                 "Banner不存在",
		UserAlreadyAnchor:              "用户已是主播",
		ShortVideoExist:                "短视频标题已存在",
		ShortVideoNonExist:             "短视频不存在",
		ShortVideoAlreadyLiked:         "已点赞,请勿重复操作",
		VipCfgExist:                    "VIP等级已存在",
		VipCfgNonExist:                 "VIP配置不存在",
		ShortVideoFileTooLarge:         "短视频文件超过大小限制",
		GameCfgExist:                   "游戏编码已存在",
		GameCfgNonExist:                "游戏配置不存在",
		AgoraCfgInvalid:                "声网配置无效",
		LiveRoomChatMuted:              "您已被禁言",
		LiveRoomCannotMuteSelf:         "不能禁言自己",
		LiveRoomAudienceNotOnline:      "该观众不在直播间",
		LiveRoomCannotKickSelf:         "不能踢出自己",
		LiveRoomKickBanned:             "您已被踢出，30分钟内不可再次进入该直播间",
		TextSensitiveWord:              "内容包含敏感词",
		AliyunTextModerationCfgInvalid: "文本审核未配置或配置无效",
		AliyunTextModerationFailed:     "文本审核服务暂不可用",
		ImageSensitiveContent:          "图片内容不合规",
		ImageModerationCfgInvalid:      "图片审核未配置或配置无效",
		ImageModerationFailed:          "图片审核服务暂不可用",
		TicketExist:                    "门票名称已存在",
		TicketNonExist:                 "门票不存在",
		PrivateRoomBillingNonExist:     "私密直播间计费配置不存在",
		LiveRoomPrivateAudienceFull:    "私密直播间观众已满",
		LiveRoomNotLive:                "直播间未在直播中",
		LiveRoomPaidDanmakuDisabled:    "付费弹幕未开启",
		ShortVideoCategoryExist:        "短视频分类名称已存在",
		ShortVideoCategoryNonExist:     "短视频分类不存在",
		ShortVideoDailyUploadLimit:     "今日上传次数已达上限,请明天再试",
	},
	lang.LangZHTW: {
		Success:                        "成功",
		EmptyUserId:                    "用戶ID不能為空",
		EmptyToken:                     "Token不能為空",
		Token:                          "Token無效或已過期",
		TestEnvClose:                   "測試環境已關閉",
		SysError:                       "系統錯誤",
		LoginFail:                      "登入失敗",
		Ban:                            "帳號已被封鎖",
		CMSLoginFail:                   "後台登入失敗",
		ServerClose:                    "伺服器關閉中,請稍後再試",
		GuildExist:                     "公會名稱已存在",
		GuildNonExist:                  "公會不存在",
		NoPermission:                   "沒有權限",
		GuildKickSelf:                  "不能剔除自己",
		GuildApplyExist:                "申請已存在或狀態不合法",
		DiamondAmountInvalid:           "鑽石數量必須為正數",
		DiamondNotEnough:               "鑽石餘額不足",
		GoldAmountInvalid:              "金幣數量必須為正數",
		GoldNotEnough:                  "金幣餘額不足",
		DiamondOverflow:                "鑽石數量溢出",
		GoldOverflow:                   "金幣數量溢出",
		LiveRoomExist:                  "直播間已存在",
		LiveRoomNotAnchor:              "您尚未成為主播",
		LiveRoomNotExist:               "直播間不存在",
		LiveRoomBanned:                 "直播間已被封禁",
		GiftExist:                      "禮物名稱已存在",
		GiftNonExist:                   "禮物不存在",
		GiftCountInvalid:               "送禮數量不合法",
		GiftOffShelf:                   "禮物已下架",
		RechargeCfgExist:               "充值配置名稱已存在",
		RechargeCfgNonExist:            "充值配置不存在",
		RechargeOrderNonExist:          "充值訂單不存在",
		RechargeAmountInvalid:          "充值金額必須為正數",
		RechargeGoldInvalid:            "充值發放金幣數必須為正數",
		RechargeOrderStateInvalid:      "訂單狀態不允許此操作",
		RechargeCfgOffShelf:            "充值配置已下架",
		InvalidParam:                   "參數無效",
		RequestTooFrequent:             "請求過於頻繁，請稍後再試",
		DailyLimitExceeded:             "超過每日發送限制，請明天再試",
		VerifyCodeInvalid:              "驗證碼無效",
		VerifyCodeExpired:              "驗證碼已過期",
		AccountAlreadyExists:           "帳號已存在",
		BannerExist:                    "Banner標題已存在",
		BannerNonExist:                 "Banner不存在",
		UserAlreadyAnchor:              "用戶已是主播",
		ShortVideoExist:                "短視頻標題已存在",
		ShortVideoNonExist:             "短視頻不存在",
		ShortVideoAlreadyLiked:         "已點讚,請勿重複操作",
		VipCfgExist:                    "VIP等級已存在",
		VipCfgNonExist:                 "VIP配置不存在",
		ShortVideoFileTooLarge:         "短視頻文件超過大小限制",
		GameCfgExist:                   "遊戲編碼已存在",
		GameCfgNonExist:                "遊戲配置不存在",
		AgoraCfgInvalid:                "聲網配置無效",
		LiveRoomChatMuted:              "您已被禁言",
		LiveRoomCannotMuteSelf:         "不能禁言自己",
		LiveRoomAudienceNotOnline:      "該觀眾不在直播間",
		LiveRoomCannotKickSelf:         "不能踢出自己",
		LiveRoomKickBanned:             "您已被踢出，30分鐘內不可再次進入該直播間",
		TextSensitiveWord:              "內容包含敏感詞",
		AliyunTextModerationCfgInvalid: "文本審核未配置或配置無效",
		AliyunTextModerationFailed:     "文本審核服務暫不可用",
		ImageSensitiveContent:          "圖片內容不合規",
		ImageModerationCfgInvalid:      "圖片審核未配置或配置無效",
		ImageModerationFailed:          "圖片審核服務暫不可用",
		TicketExist:                    "門票名稱已存在",
		TicketNonExist:                 "門票不存在",
		PrivateRoomBillingNonExist:     "私密直播間計費配置不存在",
		LiveRoomPrivateAudienceFull:    "私密直播間觀眾已滿",
		LiveRoomNotLive:                "直播間未在直播中",
		LiveRoomPaidDanmakuDisabled:    "付費彈幕未開啟",
		ShortVideoCategoryExist:        "短視頻分類名稱已存在",
		ShortVideoCategoryNonExist:     "短視頻分類不存在",
		ShortVideoDailyUploadLimit:     "今日上傳次數已達上限,請明天再試",
	},
}

// GetMsg 返回错误码在指定语言下的提示文字;
// 未匹配目标语言则回落到默认语言;再未匹配则返回空字符串
func GetMsg(code XRCode, l lang.Lang) string {
	if m, ok := codeTextMap[l]; ok {
		if s, ok2 := m[code]; ok2 {
			return s
		}
	}
	if m, ok := codeTextMap[lang.DefaultLang]; ok {
		if s, ok2 := m[code]; ok2 {
			return s
		}
	}
	return ""
}
