package errercode

import "xr-game-server/constants/lang"

func init() {
	codeTextMap[lang.LangID] = map[XRCode]string{
		Success:                         "OK",
		EmptyUserId:                     "ID pengguna wajib diisi",
		EmptyToken:                      "Token wajib diisi",
		Token:                           "Token tidak valid atau kedaluwarsa",
		TestEnvClose:                    "Lingkungan uji ditutup",
		SysError:                        "Kesalahan sistem",
		LoginFail:                       "Gagal masuk",
		Ban:                             "Akun diblokir",
		AccountCanceled:                 "Akun telah dibatalkan",
		CMSLoginFail:                    "Gagal masuk CMS",
		ServerClose:                     "Server sedang ditutup, silakan coba lagi nanti",
		GuildExist:                      "Nama guild sudah ada",
		GuildNonExist:                   "Guild tidak ditemukan",
		NoPermission:                    "Izin ditolak",
		GuildKickSelf:                   "Anda tidak dapat mengeluarkan diri sendiri",
		GuildApplyExist:                 "Permohonan sudah ada atau status tidak valid",
		DiamondAmountInvalid:            "Jumlah berlian harus positif",
		DiamondNotEnough:                "Saldo berlian tidak cukup",
		GoldAmountInvalid:               "Jumlah emas harus positif",
		GoldNotEnough:                   "Saldo emas tidak cukup",
		DiamondOverflow:                 "Jumlah berlian melebihi batas",
		GoldOverflow:                    "Jumlah emas melebihi batas",
		LiveRoomExist:                   "Ruang live sudah ada",
		LiveRoomNotAnchor:               "Anda belum menjadi anchor",
		LiveRoomNotExist:                "Ruang live tidak ditemukan",
		LiveRoomBanned:                  "Ruang live diblokir",
		LiveRoomOffShelf:                "Ruang live tidak tersedia",
		GiftExist:                       "Nama hadiah sudah ada",
		GiftNonExist:                    "Hadiah tidak ditemukan",
		GiftCountInvalid:                "Jumlah hadiah tidak valid",
		GiftOffShelf:                    "Hadiah tidak tersedia",
		RechargeCfgExist:                "Nama konfigurasi isi ulang sudah ada",
		RechargeCfgNonExist:             "Konfigurasi isi ulang tidak ditemukan",
		RechargeOrderNonExist:           "Pesanan isi ulang tidak ditemukan",
		RechargeAmountInvalid:           "Jumlah isi ulang harus positif",
		RechargeGoldInvalid:             "Jumlah emas isi ulang harus positif",
		RechargeOrderStateInvalid:       "Status pesanan tidak mengizinkan operasi ini",
		RechargeCfgOffShelf:             "Konfigurasi isi ulang tidak tersedia",
		RechargeCfgProductIdExist:       "SKU produk konfigurasi isi ulang sudah ada",
		InvalidParam:                    "Parameter tidak valid",
		RequestTooFrequent:              "Permintaan terlalu sering, silakan coba lagi nanti",
		DailyLimitExceeded:              "Batas harian terlampaui, silakan coba lagi besok",
		VerifyCodeInvalid:               "Kode verifikasi tidak valid",
		VerifyCodeExpired:               "Kode verifikasi kedaluwarsa",
		AccountAlreadyExists:            "Akun sudah ada",
		BannerExist:                     "Judul banner sudah ada",
		BannerNonExist:                  "Banner tidak ditemukan",
		UserAlreadyAnchor:               "Pengguna sudah menjadi anchor",
		ShortVideoExist:                 "Judul video pendek sudah ada",
		ShortVideoNonExist:              "Video pendek tidak ditemukan",
		ShortVideoAlreadyLiked:          "Video pendek sudah disukai",
		VipCfgExist:                     "Level VIP sudah ada",
		VipCfgNonExist:                  "Konfigurasi VIP tidak ditemukan",
		ShortVideoFileTooLarge:          "File video pendek melebihi batas ukuran",
		GameCfgExist:                    "Kode game sudah ada",
		GameCfgNonExist:                 "Konfigurasi game tidak ditemukan",
		AgoraCfgInvalid:                 "Konfigurasi Agora tidak valid",
		LiveRoomChatMuted:               "Anda dibisukan di ruang ini",
		LiveRoomCannotMuteSelf:          "Anda tidak dapat membisukan diri sendiri",
		LiveRoomAudienceNotOnline:       "Penonton tidak ada di ruang ini",
		LiveRoomCannotKickSelf:          "Anda tidak dapat mengeluarkan diri sendiri",
		LiveRoomKickBanned:              "Anda dikeluarkan dan tidak dapat masuk kembali selama 30 menit",
		TextSensitiveWord:               "Teks mengandung kata sensitif",
		AliyunTextModerationCfgInvalid:  "Konfigurasi moderasi teks tidak valid",
		AliyunTextModerationFailed:      "Layanan moderasi teks tidak tersedia",
		ImageSensitiveContent:           "Konten gambar tidak sesuai",
		ImageModerationCfgInvalid:       "Konfigurasi moderasi gambar tidak valid",
		ImageModerationFailed:           "Layanan moderasi gambar tidak tersedia",
		TicketExist:                     "Nama tiket sudah ada",
		TicketNonExist:                  "Tiket tidak ditemukan",
		PrivateRoomBillingNonExist:      "Konfigurasi penagihan ruang privat tidak ditemukan",
		LiveRoomPrivateAudienceFull:     "Penonton ruang privat penuh",
		LiveRoomNotLive:                 "Ruang live tidak sedang siaran",
		LiveRoomPaidDanmakuDisabled:     "Danmaku berbayar tidak diaktifkan",
		ShortVideoCategoryExist:         "Nama kategori video pendek sudah ada",
		ShortVideoCategoryNonExist:      "Kategori video pendek tidak ditemukan",
		ShortVideoDailyUploadLimit:      "Batas unggahan video pendek harian tercapai",
		LiveRoomTagExist:                "Nama tag ruang live sudah ada",
		LiveRoomTagNonExist:             "Tag ruang live tidak ditemukan",
		EntryEffectExist:                "Nama efek masuk sudah ada",
		EntryEffectNonExist:             "Efek masuk tidak ditemukan",
		ShortVideoMustPayToWatch:        "Video pendek ini memerlukan pembayaran untuk ditonton",
		CallUserInCall:                  "Anda sedang dalam panggilan",
		CallOrderNonExist:               "Pesanan panggilan tidak ditemukan",
		CallOrderStateInvalid:           "Status pesanan panggilan tidak mengizinkan operasi ini",
		BotAnchorNonExist:               "Anchor bot tidak ditemukan",
		NotBotAnchor:                    "Pengguna bukan anchor bot",
		AgoraCloudPlayerFailed:          "Permintaan pemutar cloud Agora gagal",
		PhoneVerifyBlocked:              "Terlalu banyak kegagalan verifikasi, silakan coba lagi dalam 2 jam",
		AppPkgExist:                     "Nama paket aplikasi sudah ada",
		AppPkgNonExist:                  "Konfigurasi paket aplikasi tidak ditemukan",
		ShortVideoOnShelfCannotDelete:   "Video pendek yang disetujui tidak dapat dihapus",
		ShortVideoOnShelfCannotUpdate:   "Video pendek yang disetujui tidak dapat diubah",
		PrivateMessageUserBlocked:       "Tidak dapat mengirim pesan pribadi karena hubungan blokir",
		ActivityMessageNonExist:         "Pesan aktivitas tidak ditemukan",
		ShortVideoDiskSpaceInsufficient: "Ruang disk tidak cukup untuk mengunggah video pendek",
		SimulatorLoginDenied:            "Login simulator tidak diizinkan",
	}
}
