package sofie

// Code generated by gen_sofie.py; DO NOT EDIT.

import (
	"xr-game-server/controller"
	"xr-game-server/core/httpserver"
)

func Init() {
	httpserver.RegAppRouteGroup("/sofie/access", []httpserver.AppRoute{
		{Path: "/replaceMobileSecret", Handler: jsonHandler((&controller.AuthAppController{}).PhoneChangePassword)},
		{Path: "/linkMailbox", Handler: jsonHandler((&controller.AuthAppController{}).BindEmail)},
		{Path: "/linkFirebase", Handler: jsonHandler((&controller.AuthAppController{}).BindFirebase)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/access", []httpserver.AppRoute{
		{Path: "/dispatchSmsOtp", Handler: jsonHandler((&controller.AuthController{}).SendCode)},
		{Path: "/dispatchMailOtp", Handler: jsonHandler((&controller.AuthController{}).SendEmailCode)},
		{Path: "/signInByMailbox", Handler: jsonHandler((&controller.AuthController{}).EmailLogin)},
		{Path: "/signInByFirebase", Handler: jsonHandler((&controller.AuthController{}).FirebaseLogin)},
		{Path: "/createPhoneAccount", Handler: jsonHandler((&controller.AuthController{}).PhoneRegister)},
		{Path: "/signInByMobile", Handler: jsonHandler((&controller.AuthController{}).PhoneLogin)},
		{Path: "/signInByDealer", Handler: jsonHandler((&controller.AuthController{}).CoinMerchantLogin)},
		{Path: "/signInByDeviceCode", Handler: jsonHandler((&controller.AuthController{}).DeviceLogin)},
		{Path: "/signInByH5Device", Handler: jsonHandler((&controller.AuthController{}).H5DeviceLogin)},
		{Path: "/resetMobileSecret", Handler: jsonHandler((&controller.AuthController{}).PhoneResetPassword)},
	})
	httpserver.RegAppRouteGroup("/sofie/bonus", []httpserver.AppRoute{
		{Path: "/fetchFirstPay", Handler: jsonHandler((&controller.FirstRechargeActivityAppController{}).FirstRechargeActivityCfgForApp)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/boot", []httpserver.AppRoute{
		{Path: "/loadConfig", Handler: jsonHandler((&controller.SysInfoController{}).GetInfo)},
	})
	httpserver.RegAppRouteGroup("/sofie/catalog", []httpserver.AppRoute{
		{Path: "/browsePackages", Handler: jsonHandler((&controller.RechargeCfgAppController{}).RechargeCfgList)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/catalog", []httpserver.AppRoute{
		{Path: "/browsePackagesByUser", Handler: jsonHandler((&controller.RechargeCfgAppPublicController{}).RechargeCfgListByUserId)},
	})
	httpserver.RegAppRouteGroup("/sofie/clip", []httpserver.AppRoute{
		{Path: "/submitMedia", Handler: controller.HandleAppPublishShortVideo},
		{Path: "/browseFeed", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoList)},
		{Path: "/browseFeedScroll", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoScroll)},
		{Path: "/browseViewed", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoViewList)},
		{Path: "/browsePublished", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoPublishList)},
		{Path: "/toggleLike", Handler: jsonHandler((&controller.ShortVideoAppController{}).LikeShortVideo)},
		{Path: "/fetchSettings", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoCfg)},
		{Path: "/beginWatch", Handler: jsonHandler((&controller.ShortVideoAppController{}).WatchShortVideoStart)},
		{Path: "/finishWatch", Handler: jsonHandler((&controller.ShortVideoAppController{}).WatchShortVideoEnd)},
		{Path: "/unlockMedia", Handler: jsonHandler((&controller.ShortVideoAppController{}).PayShortVideo)},
		{Path: "/browseWatchLog", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoWatchList)},
		{Path: "/browseCategories", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoCategoryList)},
		{Path: "/browseUploads", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoUploadRecordList)},
		{Path: "/browsePendingReview", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoPendingReviewList)},
		{Path: "/removeMedia", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppDeleteShortVideo)},
		{Path: "/browseStats", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoStatList)},
		{Path: "/browsePriceTiers", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppShortVideoPriceTierList)},
		{Path: "/browseUserFeed", Handler: jsonHandler((&controller.ShortVideoAppController{}).AppUserShortVideoList)},
	})
	httpserver.RegAppRouteGroup("/sofie/coin", []httpserver.AppRoute{
		{Path: "/swapToGem", Handler: jsonHandler((&controller.GoldAppController{}).ExchangeGoldToDiamond)},
		{Path: "/sendToUser", Handler: jsonHandler((&controller.GoldAppController{}).TransferGold)},
		{Path: "/browseDealerTransfers", Handler: jsonHandler((&controller.GoldAppController{}).GetCoinMerchantTransferRecordList)},
	})
	httpserver.RegAppRouteGroup("/sofie/dealer", []httpserver.AppRoute{
		{Path: "/browsePackages", Handler: jsonHandler((&controller.CoinMerchantRechargeCfgAppController{}).CoinMerchantRechargeCfgList)},
		{Path: "/browsePayRegions", Handler: jsonHandler((&controller.CoinMerchantRechargeCfgAppController{}).PaymentRegionList)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/googleAuth", []httpserver.AppRoute{
		{Path: "/fetchClientCfg", Handler: jsonHandler((&controller.FirebaseAppController{}).GetClientCfgForApp)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/help", []httpserver.AppRoute{
		{Path: "/fetchContact", Handler: jsonHandler((&controller.CustomerServiceAppController{}).Cfg)},
	})
	httpserver.RegAppRouteGroup("/sofie/history", []httpserver.AppRoute{
		{Path: "/browseBroadcasts", Handler: jsonHandler((&controller.LiveRecordAppController{}).AppLiveRecordList)},
	})
	httpserver.RegAppRouteGroup("/sofie/inbox", []httpserver.AppRoute{
		{Path: "/postDirectNote", Handler: jsonHandler((&controller.MessageAppController{}).SendPrivateMessage)},
		{Path: "/browseUnreadNotes", Handler: jsonHandler((&controller.MessageAppController{}).PrivateMessageUnreadList)},
		{Path: "/browseNotesByPeer", Handler: jsonHandler((&controller.MessageAppController{}).PrivateMessageBySender)},
		{Path: "/markPeerNotesRead", Handler: jsonHandler((&controller.MessageAppController{}).ClearPrivateMessageUnread)},
		{Path: "/markAllNotesRead", Handler: jsonHandler((&controller.MessageAppController{}).ClearAllPrivateMessageUnread)},
		{Path: "/removeNotesBatch", Handler: jsonHandler((&controller.MessageAppController{}).BatchDeletePrivateMessage)},
		{Path: "/browsePersonalNotices", Handler: jsonHandler((&controller.MessageAppController{}).PersonalSystemMessageList)},
		{Path: "/browseCampaignNotices", Handler: jsonHandler((&controller.MessageAppController{}).ActivityMessageList)},
		{Path: "/browseUnreadNotices", Handler: jsonHandler((&controller.MessageAppController{}).SystemMessageUnreadList)},
		{Path: "/markNoticesRead", Handler: jsonHandler((&controller.MessageAppController{}).ClearSystemMessageUnread)},
		{Path: "/countUnread", Handler: jsonHandler((&controller.MessageAppController{}).MessageUnreadCount)},
	})
	httpserver.RegAppRouteGroup("/sofie/label", []httpserver.AppRoute{
		{Path: "/browseAll", Handler: jsonHandler((&controller.LiveRoomTagAppController{}).AppLiveRoomTagList)},
		{Path: "/browseNormal", Handler: jsonHandler((&controller.LiveRoomTagAppController{}).AppLiveRoomNormalTagList)},
	})
	httpserver.RegAppRouteGroup("/sofie/member", []httpserver.AppRoute{
		{Path: "/fetchStatus", Handler: jsonHandler((&controller.VipAppController{}).GetVipDetail)},
	})
	httpserver.RegAppRouteGroup("/sofie/memberPlan", []httpserver.AppRoute{
		{Path: "/fetchTier", Handler: jsonHandler((&controller.VipCfgAppController{}).GetVipCfgByLevel)},
		{Path: "/browseTiers", Handler: jsonHandler((&controller.VipCfgAppController{}).VipCfgListForApp)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/money", []httpserver.AppRoute{
		{Path: "/browseFiats", Handler: jsonHandler((&controller.FiatCurrencyAppController{}).FiatCurrencyListForApp)},
	})
	httpserver.RegAppRouteGroup("/sofie/pass", []httpserver.AppRoute{
		{Path: "/browseTickets", Handler: jsonHandler((&controller.TicketAppController{}).AppTicketList)},
	})
	httpserver.RegAppRouteGroup("/sofie/play", []httpserver.AppRoute{
		{Path: "/browseTitles", Handler: jsonHandler((&controller.GameAppController{}).AppGameList)},
		{Path: "/openTitle", Handler: jsonHandler((&controller.GameAppController{}).AppGameStart)},
		{Path: "/browseBets", Handler: jsonHandler((&controller.GameAppController{}).AppGameBetList)},
		{Path: "/browseRoundSpend", Handler: jsonHandler((&controller.GameAppController{}).AppGameConsumeRank)},
	})
	httpserver.RegAppRouteGroup("/sofie/poster", []httpserver.AppRoute{
		{Path: "/browseHome", Handler: jsonHandler((&controller.BannerAppController{}).AppBannerList)},
	})
	httpserver.RegAppRouteGroup("/sofie/present", []httpserver.AppRoute{
		{Path: "/browseCatalog", Handler: jsonHandler((&controller.GiftAppController{}).GiftList)},
	})
	httpserver.RegAppRouteGroup("/sofie/profile", []httpserver.AppRoute{
		{Path: "/fetchMine", Handler: jsonHandler((&controller.UserInfoController{}).Get)},
		{Path: "/fetchExtra", Handler: jsonHandler((&controller.UserInfoController{}).GetUserExt)},
		{Path: "/renameNick", Handler: jsonHandler((&controller.UserInfoController{}).UpdateNickname)},
		{Path: "/changeSex", Handler: jsonHandler((&controller.UserInfoController{}).UpdateGender)},
		{Path: "/changeBirthDate", Handler: jsonHandler((&controller.UserInfoController{}).UpdateBirthday)},
		{Path: "/browseLedger", Handler: jsonHandler((&controller.UserInfoController{}).GetCurrencyLog)},
		{Path: "/closeAccount", Handler: jsonHandler((&controller.UserInfoController{}).CancelAccount)},
		{Path: "/submitOpinion", Handler: jsonHandler((&controller.UserInfoController{}).Feedback)},
		{Path: "/submitComplaint", Handler: jsonHandler((&controller.UserInfoController{}).Report)},
		{Path: "/submitAttribution", Handler: jsonHandler((&controller.UserInfoController{}).ReportAttribution)},
		{Path: "/lookupByInvite", Handler: jsonHandler((&controller.UserInfoController{}).GetUserInfoByInviteCode)},
		{Path: "/submitInviter", Handler: jsonHandler((&controller.UserInfoController{}).ReportInviter)},
		{Path: "/changePhoto", Handler: controller.HandleUploadAvatar},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/profile", []httpserver.AppRoute{
		{Path: "/closeAccountByOtp", Handler: jsonHandler((&controller.UserInfoPublicController{}).CancelAccountByCode)},
	})
	httpserver.RegAppRouteGroup("/sofie/rate", []httpserver.AppRoute{
		{Path: "/browseMinutePrices", Handler: jsonHandler((&controller.PrivateRoomBillingAppController{}).AppBillingList)},
	})
	httpserver.RegNonAuthAppRouteGroup("/sofie/release", []httpserver.AppRoute{
		{Path: "/lookupBuild", Handler: jsonHandler((&controller.AppVersionAppController{}).AppVersionQuery)},
	})
	httpserver.RegAppRouteGroup("/sofie/rtc", []httpserver.AppRoute{
		{Path: "/issueChannelToken", Handler: jsonHandler((&controller.AgoraAppController{}).LiveRoomToken)},
		{Path: "/fetchVendorId", Handler: jsonHandler((&controller.AgoraAppController{}).AppId)},
	})
	httpserver.RegAppRouteGroup("/sofie/session", []httpserver.AppRoute{
		{Path: "/inviteFromHall", Handler: jsonHandler((&controller.CallAppController{}).LiveRoomCall)},
		{Path: "/inviteDirectVideo", Handler: jsonHandler((&controller.CallAppController{}).OneToOneRoomCall)},
		{Path: "/inviteManyFromHall", Handler: jsonHandler((&controller.CallAppController{}).BatchInviteLiveRoomCall)},
		{Path: "/declineInvite", Handler: jsonHandler((&controller.CallAppController{}).AnchorRejectCall)},
		{Path: "/acceptInvite", Handler: jsonHandler((&controller.CallAppController{}).AcceptCall)},
		{Path: "/ackInvite", Handler: jsonHandler((&controller.CallAppController{}).ConfirmCall)},
		{Path: "/fetchAckState", Handler: jsonHandler((&controller.CallAppController{}).GetCallConfirmStatus)},
		{Path: "/markInviteTimeout", Handler: jsonHandler((&controller.CallAppController{}).CallTimeout)},
		{Path: "/keepAlive", Handler: jsonHandler((&controller.CallAppController{}).CallHeart)},
		{Path: "/hangUp", Handler: jsonHandler((&controller.CallAppController{}).EndCall)},
	})
	httpserver.RegAppRouteGroup("/sofie/social", []httpserver.AppRoute{
		{Path: "/addHost", Handler: jsonHandler((&controller.LiveFollowAppController{}).Follow)},
		{Path: "/removeHost", Handler: jsonHandler((&controller.LiveFollowAppController{}).Unfollow)},
		{Path: "/checkHost", Handler: jsonHandler((&controller.LiveFollowAppController{}).IsFollowing)},
		{Path: "/browseHosts", Handler: jsonHandler((&controller.LiveFollowAppController{}).FollowingList)},
		{Path: "/browseFans", Handler: jsonHandler((&controller.LiveFollowAppController{}).FollowerList)},
		{Path: "/banUser", Handler: jsonHandler((&controller.LiveFollowAppController{}).Block)},
		{Path: "/unbanUser", Handler: jsonHandler((&controller.LiveFollowAppController{}).Unblock)},
		{Path: "/browseBanned", Handler: jsonHandler((&controller.LiveFollowAppController{}).BlockList)},
	})
	httpserver.RegAppRouteGroup("/sofie/spend", []httpserver.AppRoute{
		{Path: "/browseBoard", Handler: jsonHandler((&controller.GameConsumeRankAppController{}).AppGameConsumeRankList)},
	})
	httpserver.RegAppRouteGroup("/sofie/star", []httpserver.AppRoute{
		{Path: "/browseBoard", Handler: jsonHandler((&controller.AnchorRankAppController{}).AppAnchorRankList)},
	})
	httpserver.RegAppRouteGroup("/sofie/studio", []httpserver.AppRoute{
		{Path: "/openBooth", Handler: controller.HandleCreateLiveRoom},
		{Path: "/openDirectBooth", Handler: jsonHandler((&controller.LiveRoomAppController{}).CreateOneToOneRoom)},
		{Path: "/fetchDirectBooth", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetOneToOneRoom)},
		{Path: "/beginBroadcast", Handler: jsonHandler((&controller.LiveRoomAppController{}).StartLive)},
		{Path: "/endBroadcast", Handler: jsonHandler((&controller.LiveRoomAppController{}).StopLive)},
		{Path: "/replaceCover", Handler: jsonHandler((&controller.LiveRoomAppController{}).UpdateCover)},
		{Path: "/replaceNotice", Handler: jsonHandler((&controller.LiveRoomAppController{}).UpdateNotice)},
		{Path: "/enterHall", Handler: jsonHandler((&controller.LiveRoomAppController{}).JoinRoom)},
		{Path: "/exitHall", Handler: jsonHandler((&controller.LiveRoomAppController{}).LeaveRoom)},
		{Path: "/fetchRound", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetLiveRecord)},
		{Path: "/browseAudience", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetOnlineUserList)},
		{Path: "/browseVipAudience", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetVipOnlineUserList)},
		{Path: "/browseContribution", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetContributionRank)},
		{Path: "/fetchBooth", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetRoom)},
		{Path: "/browseBooths", Handler: jsonHandler((&controller.LiveRoomAppController{}).RoomList)},
		{Path: "/browseDirectBooths", Handler: jsonHandler((&controller.LiveRoomAppController{}).OneToOneRoomList)},
		{Path: "/browseOnlineNormals", Handler: jsonHandler((&controller.LiveRoomAppController{}).ServerOnlineNormalUserList)},
		{Path: "/browseNearbyBooths", Handler: jsonHandler((&controller.LiveRoomAppController{}).NearbyRoomList)},
		{Path: "/browseHotBooths", Handler: jsonHandler((&controller.LiveRoomAppController{}).HotRoomList)},
		{Path: "/browseVoiceChatBooths", Handler: jsonHandler((&controller.LiveRoomAppController{}).VoiceChatRoomList)},
		{Path: "/fetchVoiceChatMicLayout", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetVoiceChatMicState)},
		{Path: "/requestVoiceChatMic", Handler: jsonHandler((&controller.LiveRoomAppController{}).ApplyVoiceChatMic)},
		{Path: "/cancelVoiceChatMicRequest", Handler: jsonHandler((&controller.LiveRoomAppController{}).CancelVoiceChatMicApply)},
		{Path: "/browseVoiceChatMicRequests", Handler: jsonHandler((&controller.LiveRoomAppController{}).VoiceChatMicApplyList)},
		{Path: "/acceptVoiceChatMicRequest", Handler: jsonHandler((&controller.LiveRoomAppController{}).ApproveVoiceChatMicApply)},
		{Path: "/declineVoiceChatMicRequest", Handler: jsonHandler((&controller.LiveRoomAppController{}).RejectVoiceChatMicApply)},
		{Path: "/releaseVoiceChatMic", Handler: jsonHandler((&controller.LiveRoomAppController{}).LeaveVoiceChatMic)},
		{Path: "/removeVoiceChatMicGuest", Handler: jsonHandler((&controller.LiveRoomAppController{}).KickVoiceChatMic)},
		{Path: "/applyVoiceChatMicSeatLock", Handler: jsonHandler((&controller.LiveRoomAppController{}).LockVoiceChatMicSeat)},
		{Path: "/releaseVoiceChatMicSeatLock", Handler: jsonHandler((&controller.LiveRoomAppController{}).UnlockVoiceChatMicSeat)},
		{Path: "/applyVoiceChatMicSeatMute", Handler: jsonHandler((&controller.LiveRoomAppController{}).MuteVoiceChatMicSeat)},
		{Path: "/releaseVoiceChatMicSeatMute", Handler: jsonHandler((&controller.LiveRoomAppController{}).UnmuteVoiceChatMicSeat)},
		{Path: "/seatVoiceChatMicGuest", Handler: jsonHandler((&controller.LiveRoomAppController{}).InviteVoiceChatMic)},
		{Path: "/relocateVoiceChatMicSeat", Handler: jsonHandler((&controller.LiveRoomAppController{}).SwitchVoiceChatMicSeat)},
		{Path: "/lockVoiceChatMicSeatsBatch", Handler: jsonHandler((&controller.LiveRoomAppController{}).BatchLockVoiceChatMicSeats)},
		{Path: "/unlockVoiceChatMicSeatsBatch", Handler: jsonHandler((&controller.LiveRoomAppController{}).BatchUnlockVoiceChatMicSeats)},
		{Path: "/clearVoiceChatMicRequests", Handler: jsonHandler((&controller.LiveRoomAppController{}).ClearVoiceChatMicApplies)},
		{Path: "/browseFollowedBooths", Handler: jsonHandler((&controller.LiveRoomAppController{}).FollowedRoomList)},
		{Path: "/postPresent", Handler: jsonHandler((&controller.LiveRoomAppController{}).SendGift)},
		{Path: "/postPresentToHost", Handler: jsonHandler((&controller.LiveRoomAppController{}).SendGiftToAnchor)},
		{Path: "/postChat", Handler: jsonHandler((&controller.LiveRoomAppController{}).SendChat)},
		{Path: "/postPaidBullet", Handler: jsonHandler((&controller.LiveRoomAppController{}).SendPaidDanmaku)},
		{Path: "/silenceViewer", Handler: jsonHandler((&controller.LiveRoomAppController{}).SetAudienceMute)},
		{Path: "/unsilenceViewer", Handler: jsonHandler((&controller.LiveRoomAppController{}).CancelAudienceMute)},
		{Path: "/fetchViewerRestrict", Handler: jsonHandler((&controller.LiveRoomAppController{}).GetAudienceRestrictStatus)},
		{Path: "/removeViewer", Handler: jsonHandler((&controller.LiveRoomAppController{}).KickAudience)},
		{Path: "/clearViewerBan", Handler: jsonHandler((&controller.LiveRoomAppController{}).CancelKickBan)},
		{Path: "/reportBroadcastState", Handler: jsonHandler((&controller.LiveRoomAppController{}).ReportLiveStartStatus)},
		{Path: "/browseGamePicks", Handler: jsonHandler((&controller.LiveRoomAppController{}).GameRecommendList)},
		{Path: "/submitHostCode", Handler: jsonHandler((&controller.LiveRoomAppController{}).ReportAnchorCode)},
	})
	httpserver.RegAppRouteGroup("/sofie/topup", []httpserver.AppRoute{
		{Path: "/openStoreOrder", Handler: jsonHandler((&controller.RechargeOrderAppController{}).CreateRechargeOrder)},
		{Path: "/openChannelOrder", Handler: jsonHandler((&controller.RechargeOrderAppController{}).CreateChannelRechargeOrder)},
		{Path: "/openDealerChannelOrder", Handler: jsonHandler((&controller.RechargeOrderAppController{}).CreateCoinMerchantChannelRechargeOrder)},
		{Path: "/fetchPayerProfile", Handler: jsonHandler((&controller.RechargeOrderAppController{}).GetChannelPayUserProfile)},
		{Path: "/savePayerProfile", Handler: jsonHandler((&controller.RechargeOrderAppController{}).SaveChannelPayUserProfile)},
		{Path: "/browseMyOrders", Handler: jsonHandler((&controller.RechargeOrderAppController{}).MyRechargeOrderList)},
		{Path: "/checkOrderPaid", Handler: jsonHandler((&controller.RechargeOrderAppController{}).CheckRechargeOrderSuccess)},
	})
	httpserver.RegAppRouteGroup("/sofie/wealth", []httpserver.AppRoute{
		{Path: "/browseBoard", Handler: jsonHandler((&controller.RichRankAppController{}).AppRichRankList)},
	})
	setupSofieOpenApi()
}

