package controller

import (
	"context"

	"xr-game-server/core/httpserver"
	"xr-game-server/core/xrpool"

	"github.com/gogf/gf/v2/os/gctx"
)

func Init() {
	initPushController()
	initAuthApi()
	initAuthAppController()
	initAccountController()
	initBotAnchorController()
	initGoldController()
	initGoldAppController()
	initDiamondController()
	initIndex()
	initSysController()
	initHotRestartController()
	initAppTokenController()
	initRoleController()                         // 添加角色控制器初始化
	initCMSUserController()                      // 添加CMS用户控制器初始化
	initUserInfoController()                     // 用户基础信息(App)
	initUserInfoPublicController()               // 用户公开接口(官网销户等)
	initGuildController()                        // 直播工会管理(CMS)
	initLiveRoomAppController()                  // 直播间(App)
	initLiveRoomTagController()                  // 直播间标签(CMS)
	initLiveRoomTagAppController()               // 直播间标签(App)
	initAgoraAppController()                     // 声网(App)
	initCallAppController()                      // 通话(App)
	initCallCMSController()                      // 通话(CMS)
	initAgoraCMSController()                     // 声网(CMS)
	initLiveCfgCMSController()                   // 直播配置(CMS)
	initAliyunTextModerationCMSController()      // 阿里云文本审核(CMS)
	initPrivacyPolicyCMSController()             // 隐私政策配置(CMS)
	initGooglePlayCMSController()                // Google Play 配置(CMS)
	initDataSyncCMSController()                  // 数据同步配置(CMS)
	initDataSyncReceiveController()              // 数据同步接收(跨环境)
	initGooglePlayWebhookController()            // Google Play RTDN Webhook
	initCustomerServiceCMSController()           // 客服联系配置(CMS)
	initCustomerServiceAppController()           // 客服联系配置(App)
	initWalletCMSController()                    // 钱包配置(CMS)
	initAccountCfgCMSController()                // 账号配置(CMS)
	initFirstRechargeActivityCMSController()     // 首充活动配置(CMS)
	initFirstRechargeActivityAppController()     // 首充活动配置(App)
	initSimulatorCpuKeywordCMSController()       // 模拟器CPU关键词(CMS)
	initAnchorSalaryCfgCMSController()           // 主播结算薪资分档配置(CMS)
	initLiveRevenueShareCfgCMSController()       // 流水分佣配置(CMS)
	initPreloadCfgCMSController()                // 预热配置(CMS)
	initGiftController()                         // 礼物配置(CMS)
	initGiftAppController()                      // 礼物列表(App)
	initBannerController()                       // 首页Banner(CMS)
	initActivityMessageController()              // 活动消息(CMS)
	initBannerAppController()                    // 首页Banner(App)
	initTicketController()                       // 门票(CMS)
	initTicketAppController()                    // 门票(App)
	initPrivateRoomBillingController()           // 私密直播间计费(CMS)
	initPrivateRoomBillingAppController()        // 私密直播间计费(App)
	initShortVideoController()                   // 短视频(CMS)
	initShortVideoAppController()                // 短视频(App)
	initLiveFollowAppController()                // 关注主播(App)
	initRechargeCfgController()                  // 充值配置管理(CMS)
	initRechargeCfgAppController()               // 充值配置查询(App)
	initRechargeOrderController()                // 充值订单(CMS:查询/手动充值)
	initCurrencyLogController()                  // 货币流水(CMS)
	initLiveRevenueLogController()               // 直播收益流水(CMS)
	initAnchorIncomeSettlementLogCMSController() // 主播结算流水(CMS)
	initGuildIncomeSettlementLogCMSController()  // 工会结算流水(CMS)
	initLiveRecordCMSController()                // 直播记录(CMS)
	initLiveRecordAppController()                // 直播记录(App)
	initRichRankAppController()                  // 富豪榜(App)
	initAnchorRankAppController()                // 主播红人榜(App)
	initRechargeOrderAppController()             // 充值订单(App:发起/查询)
	initVipCfgController()                       // VIP配置(CMS)
	initAppPkgController()                       // App包管理(CMS)
	initGameAppController()                      // 游戏列表(App)
	initGamePlatformCMSController()              // 游戏平台接入配置(CMS)
	initGameWinLogCMSController()                // 游戏派彩记录(CMS)
	initGameBetLogCMSController()                // 游戏下注记录(CMS)
	initGameVendorCallbackController()           // 游戏第三方回调(verify/balance)
	initVipCfgAppController()                    // VIP配置查询(App)
	initVipAppController()                       // VIP详情(App)
	initMessageAppController()                   // 私信(App)
	initUploadController()                       // CMS文件上传
	initH5LiveDeployCMSController()              // H5直播静态资源部署(CMS)
	initRandomNicknameController()               // 随机昵称库(CMS)
	initSysStatController()                      // 系统总数据/仪表盘(CMS)
	initResourceMetricController()               // 系统资源监控(CMS)
	initLogQueryController()                     // 日志查询(CMS)
	initCMSExportController()                    // CMS异步导出
	httpserver.InitWebsocket()
	xrpool.AddWithRecover(gctx.New(), func(ctx context.Context) {
		httpserver.InitHttpServer()
	})
}
