package entity

func Init() {
	initAccount()
	InitCMSUser()
	initGlobalCfg()
	initRank()
	initName()
	InitCMSRole()
	InitPermission()
	initUserInfo()
	initCurrencyLog()
	InitLiveGuild()
	initGuildMember()
	initLiveRoom()
	initLiveRoomOnline()
	InitLiveGift()
	initHomeBanner()
	initShortVideo()
	initShortVideoLike()
	initLiveFollow()
	initRechargeCfg()
	initRechargeOrder()
	initVipCfg()
}
