package currency

// reasonTextMap 货币变动原因的多语言文案表
// 新增枚举值时,请同步在每个语言映射中补全对应文案
var reasonTextMap = map[Lang]map[Reason]string{
	LangZHCN: {
		ReasonUnknown:                  "未知",
		ReasonRecharge:                 "充值",
		ReasonRechargeFirstBonus:       "档位首充",
		ReasonRechargeTier:             "档位充值",
		ReasonRechargeCustom:           "自定义金额充值",
		ReasonRechargeGoogle:           "Google Play充值",
		ReasonRechargeIOS:              "iOS充值",
		ReasonRechargeChannel:          "渠道充值",
		ReasonRechargeWhitelist:        "白名单充值",
		ReasonRechargeManual:           "后台手动充值",
		ReasonShopBuy:                  "商城购买",
		ReasonTaskReward:               "任务奖励",
		ReasonRankReward:               "排行榜奖励",
		ReasonMailAttachment:           "邮件附件",
		ReasonGmAdjustTest:           "GM调整-测试",
		ReasonGmAdjustCompensation:   "GM调整-补偿",
		ReasonGuildContribute:          "工会贡献",
		ReasonRefund:                   "退款返还",
		ReasonSystemGrant:              "系统发放",
		ReasonGiftSend:                 "直播间送礼",
		ReasonGoldExchange:             "金币兑换钻石",
		ReasonShortVideoWatch:          "短视频观看",
		ReasonAnchorGiftRevenue:        "主播收到礼物收益",
		ReasonPrivateRoomTicket:        "私密直播间门票",
		ReasonPrivateRoomBilling:       "私密直播间计费",
		ReasonPaidDanmaku:              "直播间付费弹幕",
		ReasonLiveRoomVideoCallTicket:  "直播间视频通话门票",
		ReasonLiveRoomVideoCallBilling: "直播间视频通话计费",
		ReasonGameBet:                  "游戏消费",
		ReasonGameBetWin:               "游戏奖励",
		ReasonShortVideoAuthorSettlement: "短视频作者结算",
	},
	LangZHTW: {
		ReasonUnknown:                  "未知",
		ReasonRecharge:                 "儲值",
		ReasonRechargeFirstBonus:       "檔位首充",
		ReasonRechargeTier:             "檔位充值",
		ReasonRechargeCustom:           "自訂金額充值",
		ReasonRechargeGoogle:           "Google Play儲值",
		ReasonRechargeIOS:              "iOS儲值",
		ReasonRechargeChannel:          "渠道儲值",
		ReasonRechargeWhitelist:        "白名單儲值",
		ReasonRechargeManual:           "後台手動儲值",
		ReasonShopBuy:                  "商城購買",
		ReasonTaskReward:               "任務獎勵",
		ReasonRankReward:               "排行榜獎勵",
		ReasonMailAttachment:           "郵件附件",
		ReasonGmAdjustTest:           "GM調整-測試",
		ReasonGmAdjustCompensation:   "GM調整-補償",
		ReasonGuildContribute:          "公會貢獻",
		ReasonRefund:                   "退款返還",
		ReasonSystemGrant:              "系統發放",
		ReasonGiftSend:                 "直播間送禮",
		ReasonGoldExchange:             "金幣兌換鑽石",
		ReasonShortVideoWatch:          "短視頻觀看",
		ReasonAnchorGiftRevenue:        "主播收到禮物收益",
		ReasonPrivateRoomTicket:        "私密直播間門票",
		ReasonPrivateRoomBilling:       "私密直播間計費",
		ReasonPaidDanmaku:              "直播間付費彈幕",
		ReasonLiveRoomVideoCallTicket:  "直播間視頻通話門票",
		ReasonLiveRoomVideoCallBilling: "直播間視頻通話計費",
		ReasonGameBet:                  "遊戲消費",
		ReasonGameBetWin:               "遊戲獎勵",
		ReasonShortVideoAuthorSettlement: "短視頻作者結算",
	},
	LangEN: {
		ReasonUnknown:                  "Unknown",
		ReasonRecharge:                 "Recharge",
		ReasonRechargeFirstBonus:       "Tier First Recharge",
		ReasonRechargeTier:             "Tier Recharge",
		ReasonRechargeCustom:           "Custom Amount Recharge",
		ReasonRechargeGoogle:           "Google Play Recharge",
		ReasonRechargeIOS:              "iOS Recharge",
		ReasonRechargeChannel:          "Channel Recharge",
		ReasonRechargeWhitelist:        "Whitelist Recharge",
		ReasonRechargeManual:           "Manual Recharge",
		ReasonShopBuy:                  "Shop Purchase",
		ReasonTaskReward:               "Task Reward",
		ReasonRankReward:               "Rank Reward",
		ReasonMailAttachment:           "Mail Attachment",
		ReasonGmAdjustTest:           "GM Adjustment (Test)",
		ReasonGmAdjustCompensation:   "GM Adjustment (Compensation)",
		ReasonGuildContribute:          "Guild Contribution",
		ReasonRefund:                   "Refund",
		ReasonSystemGrant:              "System Grant",
		ReasonGiftSend:                 "Live Room Gift",
		ReasonGoldExchange:             "Gold to Diamond Exchange",
		ReasonShortVideoWatch:          "Short Video Watch",
		ReasonAnchorGiftRevenue:        "Anchor Gift Revenue",
		ReasonPrivateRoomTicket:        "Private Room Ticket",
		ReasonPrivateRoomBilling:       "Private Room Billing",
		ReasonPaidDanmaku:              "Live Room Paid Danmaku",
		ReasonLiveRoomVideoCallTicket:  "Live Room Video Call Ticket",
		ReasonLiveRoomVideoCallBilling: "Live Room Video Call Billing",
		ReasonGameBet:                  "Game Bet",
		ReasonGameBetWin:               "Game Bet Win",
		ReasonShortVideoAuthorSettlement: "Short Video Author Settlement",
	},
	LangID: {
		ReasonUnknown:                  "Tidak diketahui",
		ReasonRecharge:                 "Isi ulang",
		ReasonRechargeFirstBonus:       "Isi ulang pertama tier",
		ReasonRechargeTier:             "Isi ulang tier",
		ReasonRechargeCustom:           "Isi ulang jumlah kustom",
		ReasonRechargeGoogle:           "Isi ulang Google Play",
		ReasonRechargeIOS:              "Isi ulang iOS",
		ReasonRechargeChannel:          "Isi ulang channel",
		ReasonRechargeWhitelist:        "Isi ulang whitelist",
		ReasonRechargeManual:           "Isi ulang manual",
		ReasonShopBuy:                  "Pembelian toko",
		ReasonTaskReward:               "Hadiah tugas",
		ReasonRankReward:               "Hadiah peringkat",
		ReasonMailAttachment:           "Lampiran surat",
		ReasonGmAdjustTest:           "Penyesuaian GM (Tes)",
		ReasonGmAdjustCompensation:   "Penyesuaian GM (Kompensasi)",
		ReasonGuildContribute:          "Kontribusi guild",
		ReasonRefund:                   "Pengembalian dana",
		ReasonSystemGrant:              "Pemberian sistem",
		ReasonGiftSend:                 "Hadiah ruang live",
		ReasonGoldExchange:             "Tukar emas ke berlian",
		ReasonShortVideoWatch:          "Menonton video pendek",
		ReasonAnchorGiftRevenue:        "Pendapatan hadiah anchor",
		ReasonPrivateRoomTicket:        "Tiket ruang privat",
		ReasonPrivateRoomBilling:       "Penagihan ruang privat",
		ReasonPaidDanmaku:              "Danmaku berbayar ruang live",
		ReasonLiveRoomVideoCallTicket:  "Tiket panggilan video ruang live",
		ReasonLiveRoomVideoCallBilling: "Penagihan panggilan video ruang live",
		ReasonGameBet:                  "Taruhan game",
		ReasonGameBetWin:               "Kemenangan taruhan game",
		ReasonShortVideoAuthorSettlement: "Penyelesaian pendapatan video pendek",
	},
}

// Text 返回当前枚举在指定语言下的文案;未匹配时回落到默认语言,再不匹配则返回 String()
func (r Reason) Text(lang Lang) string {
	if m, ok := reasonTextMap[lang]; ok {
		if s, ok2 := m[r]; ok2 {
			return s
		}
	}
	if m, ok := reasonTextMap[DefaultLang]; ok {
		if s, ok2 := m[r]; ok2 {
			return s
		}
	}
	return r.String()
}
