package statdao

func Init() {
	initSysSata()
	initDailyLoginStatDao()
	initDailyUserLoginDao()
	initDailyUserRechargeDao()
	initDailyUserGoldConsumeDao()
	initDailyUserDiamondConsumeDao()
	initDailyUserAudienceDao()
	initWeeklyLoginStatDao()
	initWeeklyUserLoginDao()
	initWeeklyUserRechargeDao()
	initWeeklyUserGoldConsumeDao()
	initWeeklyUserDiamondConsumeDao()
	initWeeklyUserAudienceDao()
	initMonthlyLoginStatDao()
	initMonthlyUserLoginDao()
	initMonthlyUserRechargeDao()
	initMonthlyUserGoldConsumeDao()
	initMonthlyUserDiamondConsumeDao()
	initMonthlyUserAudienceDao()
	initDailyHotLiveRoomJoinStatDao()
	initWeeklyHotLiveRoomJoinStatDao()
	initMonthlyHotLiveRoomJoinStatDao()
	initDailyLiveFirstFrameRenderStatDao()
	initWeeklyLiveFirstFrameRenderStatDao()
	initMonthlyLiveFirstFrameRenderStatDao()
	initDailyHotLiveRoomLeaveStatDao()
	initWeeklyHotLiveRoomLeaveStatDao()
	initMonthlyHotLiveRoomLeaveStatDao()
	initDailyCall1v1InitiateStatDao()
	initWeeklyCall1v1InitiateStatDao()
	initMonthlyCall1v1InitiateStatDao()
}
