package country

// 静态国家/地区全量表(ISO 3166-1 alpha-2)。
// 字段: Code 简码 / NameEn 英文名 / NameZh 中文名 / FlagIcon 文件名(如 id.png)。
// EU 为支付特例区域码; 完整路径见 RelPath(code, version)。
var all = []Country{
	// —— 亚洲 Asia ——
	newCountry("AE", "United Arab Emirates", "阿联酋"),
	newCountry("AF", "Afghanistan", "阿富汗"),
	newCountry("AM", "Armenia", "亚美尼亚"),
	newCountry("AZ", "Azerbaijan", "阿塞拜疆"),
	newCountry("BD", "Bangladesh", "孟加拉国"),
	newCountry("BH", "Bahrain", "巴林"),
	newCountry("BN", "Brunei", "文莱"),
	newCountry("BT", "Bhutan", "不丹"),
	newCountry("CN", "China", "中国"),
	newCountry("CY", "Cyprus", "塞浦路斯"),
	newCountry("GE", "Georgia", "格鲁吉亚"),
	newCountry("HK", "Hong Kong", "中国香港"),
	newCountry("ID", "Indonesia", "印尼"),
	newCountry("IL", "Israel", "以色列"),
	newCountry("IN", "India", "印度"),
	newCountry("IQ", "Iraq", "伊拉克"),
	newCountry("IR", "Iran", "伊朗"),
	newCountry("JO", "Jordan", "约旦"),
	newCountry("JP", "Japan", "日本"),
	newCountry("KG", "Kyrgyzstan", "吉尔吉斯斯坦"),
	newCountry("KH", "Cambodia", "柬埔寨"),
	newCountry("KP", "North Korea", "朝鲜"),
	newCountry("KR", "South Korea", "韩国"),
	newCountry("KW", "Kuwait", "科威特"),
	newCountry("KZ", "Kazakhstan", "哈萨克斯坦"),
	newCountry("LA", "Laos", "老挝"),
	newCountry("LB", "Lebanon", "黎巴嫩"),
	newCountry("LK", "Sri Lanka", "斯里兰卡"),
	newCountry("MM", "Myanmar", "缅甸"),
	newCountry("MN", "Mongolia", "蒙古"),
	newCountry("MO", "Macao", "中国澳门"),
	newCountry("MV", "Maldives", "马尔代夫"),
	newCountry("MY", "Malaysia", "马来西亚"),
	newCountry("NP", "Nepal", "尼泊尔"),
	newCountry("OM", "Oman", "阿曼"),
	newCountry("PH", "Philippines", "菲律宾"),
	newCountry("PK", "Pakistan", "巴基斯坦"),
	newCountry("PS", "Palestine", "巴勒斯坦"),
	newCountry("QA", "Qatar", "卡塔尔"),
	newCountry("SA", "Saudi Arabia", "沙特阿拉伯"),
	newCountry("SG", "Singapore", "新加坡"),
	newCountry("SY", "Syria", "叙利亚"),
	newCountry("TH", "Thailand", "泰国"),
	newCountry("TJ", "Tajikistan", "塔吉克斯坦"),
	newCountry("TL", "Timor-Leste", "东帝汶"),
	newCountry("TM", "Turkmenistan", "土库曼斯坦"),
	newCountry("TR", "Turkiye", "土耳其"),
	newCountry("UZ", "Uzbekistan", "乌兹别克斯坦"),
	newCountry("VN", "Vietnam", "越南"),
	newCountry("YE", "Yemen", "也门"),

	// —— 欧洲 Europe ——
	newCountry("AD", "Andorra", "安道尔"),
	newCountry("AL", "Albania", "阿尔巴尼亚"),
	newCountry("AT", "Austria", "奥地利"),
	newCountry("AX", "Åland Islands", "奥兰"),
	newCountry("BA", "Bosnia and Herzegovina", "波黑"),
	newCountry("BE", "Belgium", "比利时"),
	newCountry("BG", "Bulgaria", "保加利亚"),
	newCountry("BY", "Belarus", "白俄罗斯"),
	newCountry("CH", "Switzerland", "瑞士"),
	newCountry("CZ", "Czechia", "捷克"),
	newCountry("DE", "Germany", "德国"),
	newCountry("DK", "Denmark", "丹麦"),
	newCountry("EE", "Estonia", "爱沙尼亚"),
	newCountry("ES", "Spain", "西班牙"),
	newCountry("FI", "Finland", "芬兰"),
	newCountry("FO", "Faroe Islands", "法罗群岛"),
	newCountry("FR", "France", "法国"),
	newCountry("GB", "United Kingdom", "英国"),
	newCountry("GG", "Guernsey", "根西"),
	newCountry("GI", "Gibraltar", "直布罗陀"),
	newCountry("GR", "Greece", "希腊"),
	newCountry("HR", "Croatia", "克罗地亚"),
	newCountry("HU", "Hungary", "匈牙利"),
	newCountry("IE", "Ireland", "爱尔兰"),
	newCountry("IM", "Isle of Man", "马恩岛"),
	newCountry("IS", "Iceland", "冰岛"),
	newCountry("IT", "Italy", "意大利"),
	newCountry("JE", "Jersey", "泽西"),
	newCountry("LI", "Liechtenstein", "列支敦士登"),
	newCountry("LT", "Lithuania", "立陶宛"),
	newCountry("LU", "Luxembourg", "卢森堡"),
	newCountry("LV", "Latvia", "拉脱维亚"),
	newCountry("MC", "Monaco", "摩纳哥"),
	newCountry("MD", "Moldova", "摩尔多瓦"),
	newCountry("ME", "Montenegro", "黑山"),
	newCountry("MK", "North Macedonia", "北马其顿"),
	newCountry("MT", "Malta", "马耳他"),
	newCountry("NL", "Netherlands, Kingdom of the", "荷兰"),
	newCountry("NO", "Norway", "挪威"),
	newCountry("PL", "Poland", "波兰"),
	newCountry("PT", "Portugal", "葡萄牙"),
	newCountry("RO", "Romania", "罗马尼亚"),
	newCountry("RS", "Serbia", "塞尔维亚"),
	newCountry("RU", "Russia", "俄罗斯"),
	newCountry("SE", "Sweden", "瑞典"),
	newCountry("SI", "Slovenia", "斯洛文尼亚"),
	newCountry("SJ", "Svalbard and Jan Mayen", "斯瓦尔巴和扬马延"),
	newCountry("SK", "Slovakia", "斯洛伐克"),
	newCountry("SM", "San Marino", "圣马力诺"),
	newCountry("UA", "Ukraine", "乌克兰"),
	newCountry("VA", "Vatican City", "梵蒂冈"),

	// —— 非洲 Africa ——
	newCountry("AO", "Angola", "安哥拉"),
	newCountry("BF", "Burkina Faso", "布基纳法索"),
	newCountry("BI", "Burundi", "布隆迪"),
	newCountry("BJ", "Benin", "贝宁"),
	newCountry("BW", "Botswana", "博茨瓦纳"),
	newCountry("CD", "Congo (DRC)", "刚果（金）"),
	newCountry("CF", "Central African Republic", "中非"),
	newCountry("CG", "Congo", "刚果（布）"),
	newCountry("CI", "Cote d'Ivoire", "科特迪瓦"),
	newCountry("CM", "Cameroon", "喀麦隆"),
	newCountry("CV", "Cape Verde", "佛得角"),
	newCountry("DJ", "Djibouti", "吉布提"),
	newCountry("DZ", "Algeria", "阿尔及利亚"),
	newCountry("EG", "Egypt", "埃及"),
	newCountry("EH", "Western Sahara", "阿拉伯撒哈拉民主共和国"),
	newCountry("ER", "Eritrea", "厄立特里亚"),
	newCountry("ET", "Ethiopia", "埃塞俄比亚"),
	newCountry("GA", "Gabon", "加蓬"),
	newCountry("GH", "Ghana", "加纳"),
	newCountry("GM", "Gambia", "冈比亚"),
	newCountry("GN", "Guinea", "几内亚"),
	newCountry("GQ", "Equatorial Guinea", "赤道几内亚"),
	newCountry("GW", "Guinea-Bissau", "几内亚比绍"),
	newCountry("IO", "British Indian Ocean Territory", "英属印度洋领地"),
	newCountry("KE", "Kenya", "肯尼亚"),
	newCountry("KM", "Comoros", "科摩罗"),
	newCountry("LR", "Liberia", "利比里亚"),
	newCountry("LS", "Lesotho", "莱索托"),
	newCountry("LY", "Libya", "利比亚"),
	newCountry("MA", "Morocco", "摩洛哥"),
	newCountry("MG", "Madagascar", "马达加斯加"),
	newCountry("ML", "Mali", "马里"),
	newCountry("MR", "Mauritania", "毛里塔尼亚"),
	newCountry("MU", "Mauritius", "毛里求斯"),
	newCountry("MW", "Malawi", "马拉维"),
	newCountry("MZ", "Mozambique", "莫桑比克"),
	newCountry("NA", "Namibia", "纳米比亚"),
	newCountry("NE", "Niger", "尼日尔"),
	newCountry("NG", "Nigeria", "尼日利亚"),
	newCountry("RE", "Réunion", "留尼汪"),
	newCountry("RW", "Rwanda", "卢旺达"),
	newCountry("SC", "Seychelles", "塞舌尔"),
	newCountry("SD", "Sudan", "苏丹"),
	newCountry("SH", "Saint Helena", "圣赫勒拿、阿森松和特里斯坦-达库尼亚"),
	newCountry("SL", "Sierra Leone", "塞拉利昂"),
	newCountry("SN", "Senegal", "塞内加尔"),
	newCountry("SO", "Somalia", "索马里"),
	newCountry("SS", "South Sudan", "南苏丹"),
	newCountry("ST", "Sao Tome and Principe", "圣多美和普林西比"),
	newCountry("SZ", "Eswatini", "斯威士兰"),
	newCountry("TD", "Chad", "乍得"),
	newCountry("TF", "French Southern Territories", "法属南部领地"),
	newCountry("TG", "Togo", "多哥"),
	newCountry("TN", "Tunisia", "突尼斯"),
	newCountry("TZ", "Tanzania", "坦桑尼亚"),
	newCountry("UG", "Uganda", "乌干达"),
	newCountry("YT", "Mayotte", "马约特"),
	newCountry("ZA", "South Africa", "南非"),
	newCountry("ZM", "Zambia", "赞比亚"),
	newCountry("ZW", "Zimbabwe", "津巴布韦"),

	// —— 美洲 Americas ——
	newCountry("AG", "Antigua and Barbuda", "安提瓜和巴布达"),
	newCountry("AI", "Anguilla", "安圭拉"),
	newCountry("AR", "Argentina", "阿根廷"),
	newCountry("AW", "Aruba", "阿鲁巴"),
	newCountry("BB", "Barbados", "巴巴多斯"),
	newCountry("BL", "Saint Barthélemy", "圣巴泰勒米"),
	newCountry("BM", "Bermuda", "百慕大"),
	newCountry("BO", "Bolivia", "玻利维亚"),
	newCountry("BQ", "Caribbean Netherlands", "荷兰加勒比区"),
	newCountry("BR", "Brazil", "巴西"),
	newCountry("BS", "Bahamas", "巴哈马"),
	newCountry("BV", "Bouvet Island", "布韦岛"),
	newCountry("BZ", "Belize", "伯利兹"),
	newCountry("CA", "Canada", "加拿大"),
	newCountry("CL", "Chile", "智利"),
	newCountry("CO", "Colombia", "哥伦比亚"),
	newCountry("CR", "Costa Rica", "哥斯达黎加"),
	newCountry("CU", "Cuba", "古巴"),
	newCountry("CW", "Curaçao", "库拉索"),
	newCountry("DM", "Dominica", "多米尼克"),
	newCountry("DO", "Dominican Republic", "多米尼加"),
	newCountry("EC", "Ecuador", "厄瓜多尔"),
	newCountry("FK", "Falkland Islands", "福克兰群岛"),
	newCountry("GD", "Grenada", "格林纳达"),
	newCountry("GF", "French Guiana", "法属圭亚那"),
	newCountry("GL", "Greenland", "格陵兰"),
	newCountry("GP", "Guadeloupe", "瓜德罗普"),
	newCountry("GS", "South Georgia and South Sandwich Islands", "南乔治亚和南桑威奇群岛"),
	newCountry("GT", "Guatemala", "危地马拉"),
	newCountry("GY", "Guyana", "圭亚那"),
	newCountry("HN", "Honduras", "洪都拉斯"),
	newCountry("HT", "Haiti", "海地"),
	newCountry("JM", "Jamaica", "牙买加"),
	newCountry("KN", "Saint Kitts and Nevis", "圣基茨和尼维斯"),
	newCountry("KY", "Cayman Islands", "开曼群岛"),
	newCountry("LC", "Saint Lucia", "圣卢西亚"),
	newCountry("MF", "Saint Martin", "法属圣马丁"),
	newCountry("MQ", "Martinique", "马提尼克"),
	newCountry("MS", "Montserrat", "蒙特塞拉特"),
	newCountry("MX", "Mexico", "墨西哥"),
	newCountry("NI", "Nicaragua", "尼加拉瓜"),
	newCountry("PA", "Panama", "巴拿马"),
	newCountry("PE", "Peru", "秘鲁"),
	newCountry("PM", "Saint Pierre and Miquelon", "圣皮埃尔和密克隆"),
	newCountry("PR", "Puerto Rico", "波多黎各"),
	newCountry("PY", "Paraguay", "巴拉圭"),
	newCountry("SR", "Suriname", "苏里南"),
	newCountry("SV", "El Salvador", "萨尔瓦多"),
	newCountry("SX", "Sint Maarten", "荷属圣马丁"),
	newCountry("TC", "Turks and Caicos Islands", "特克斯和凯科斯群岛"),
	newCountry("TT", "Trinidad and Tobago", "特立尼达和多巴哥"),
	newCountry("US", "United States", "美国"),
	newCountry("UY", "Uruguay", "乌拉圭"),
	newCountry("VC", "Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯"),
	newCountry("VE", "Venezuela", "委内瑞拉"),
	newCountry("VG", "British Virgin Islands", "英属维尔京群岛"),
	newCountry("VI", "U.S. Virgin Islands", "美属维尔京群岛"),

	// —— 大洋洲 Oceania ——
	newCountry("AS", "American Samoa", "美属萨摩亚"),
	newCountry("AU", "Australia", "澳大利亚"),
	newCountry("CC", "Cocos (Keeling) Islands", "科科斯（基林）群岛"),
	newCountry("CK", "Cook Islands", "库克群岛"),
	newCountry("CX", "Christmas Island", "圣诞岛"),
	newCountry("FJ", "Fiji", "斐济"),
	newCountry("FM", "Micronesia", "密克罗尼西亚联邦"),
	newCountry("GU", "Guam", "关岛"),
	newCountry("HM", "Heard Island and McDonald Islands", "赫德岛和麦克唐纳群岛"),
	newCountry("KI", "Kiribati", "基里巴斯"),
	newCountry("MH", "Marshall Islands", "马绍尔群岛"),
	newCountry("MP", "Northern Mariana Islands", "北马里亚纳群岛"),
	newCountry("NC", "New Caledonia", "新喀里多尼亚"),
	newCountry("NF", "Norfolk Island", "诺福克岛"),
	newCountry("NR", "Nauru", "瑙鲁"),
	newCountry("NU", "Niue", "纽埃"),
	newCountry("NZ", "New Zealand", "新西兰"),
	newCountry("PF", "French Polynesia", "法属波利尼西亚"),
	newCountry("PG", "Papua New Guinea", "巴布亚新几内亚"),
	newCountry("PN", "Pitcairn", "皮特凯恩群岛"),
	newCountry("PW", "Palau", "帕劳"),
	newCountry("SB", "Solomon Islands", "所罗门群岛"),
	newCountry("TK", "Tokelau", "托克劳"),
	newCountry("TO", "Tonga", "汤加"),
	newCountry("TV", "Tuvalu", "图瓦卢"),
	newCountry("UM", "U.S. Minor Outlying Islands", "美国本土外小岛屿"),
	newCountry("VU", "Vanuatu", "瓦努阿图"),
	newCountry("WF", "Wallis and Futuna", "瓦利斯和富图纳"),
	newCountry("WS", "Samoa", "萨摩亚"),

	// —— 其它 / 特例 ——
	newCountry("AQ", "Antarctica", "南极洲"),
	newCountry("EU", "European Union", "欧盟"), // 支付特例,非 ISO 主权国家
	newCountry("TW", "Taiwan", "台湾"),
}

var byCode map[string]Country

func init() {
	byCode = make(map[string]Country, len(all))
	for _, c := range all {
		byCode[c.Code] = c
	}
}
