// Code generated from HaiPay 代付支付方式列表，仅包含状态为“可用”的方式; DO NOT EDIT.
// Source: https://doc.haipay.net/docs/zh/api/version2/cashout_code_list
package country

var haiPayPayoutOptions = []HaiPayPayoutOption{
	{
		CountryCode: "US",
		Currency:    "USD",
		Region:      HaiPayPayoutRegionNorthAmerica,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "VENMO", Limit: "1-800", Description: "Venmo钱包"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ACH", Limit: "10-200000", Description: "ACH转账"},
			{AccountType: "EWALLET", BankCode: "ECASHAPP", Limit: "30-800", Description: "CashApp钱包"},
		},
	},
	{
		CountryCode: "EU",
		Currency:    "EUR",
		Region:      HaiPayPayoutRegionEurope,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "BANK_ACCOUNT", BankCode: "SEPA_BANK_USD_FX", Limit: "1-150000", Description: "SEPA 银行转账（扣美元余额，换汇后支付欧元）"},
		},
	},
	{
		CountryCode: "BR",
		Currency:    "BRL",
		Region:      HaiPayPayoutRegionSouthAmerica,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "PIX", Limit: "5-20000", Description: "PIX"},
		},
	},
	{
		CountryCode: "KR",
		Currency:    "KRW",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "BANK_ACCOUNT", BankCode: "KOPOKRS1", Limit: "1000-1500000", Description: "Korea Post(Epost)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KWABKRSE", Limit: "1000-1500000", Description: "Kwangju Bank(KJ)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KYNAKR22", Limit: "1000-1500000", Description: "Kyongnam Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NACFKRSE", Limit: "1000-1500000", Description: "Nonghyup Bank(NH)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NFFCKRSE", Limit: "1000-1500000", Description: "Suhyup Local Cooperatives"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PUSBKR2P", Limit: "1000-1500000", Description: "Busan Bank(BNK)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KODBKRSE", Limit: "1000-1500000", Description: "Korea Development Bank(KDB)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCBLKRSE", Limit: "1000-1500000", Description: "Standard Chartered Korea(SC First)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SHBKKRSE", Limit: "1000-1500000", Description: "Shinhan Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SSISKRSS", Limit: "1000-1500000", Description: "Shinhan Investment"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HVBKKRSE", Limit: "1000-1500000", Description: "Woori Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CITIKRSXKAK", Limit: "1000-1500000", Description: "K Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CZNBKRSE", Limit: "1000-1500000", Description: "Kookmin-Bank(KB)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DAEBKR22", Limit: "1000-1500000", Description: "Daegu Bank(DGB)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DEUTKRSE", Limit: "1000-1500000", Description: "Deutsche Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ETSIKRS1", Limit: "1000-1500000", Description: "eBEST Investment and Securities"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HNBNKRSE", Limit: "1000-1500000", Description: "KEB Hana Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HSBCKRSE", Limit: "1000-1500000", Description: "HSBC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CITIKRSX", Limit: "1000-1500000", Description: "Citibank Korea"},
			{AccountType: "BANK_ACCOUNT", BankCode: "IBKOKRSE", Limit: "1000-1500000", Description: "Industrial Bank of Korea(IBK)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JEONKRSE", Limit: "1000-1500000", Description: "Jeonbuk Bank(JB)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JJBKKR22", Limit: "1000-1500000", Description: "Jeju Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KAKOKR22", Limit: "1000-1500000", Description: "KAKAO Bank"},
		},
	},
	{
		CountryCode: "PH",
		Currency:    "PHP",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "GCASH", Limit: "1-50000", Description: "Gcash钱包"},
			{AccountType: "EWALLET", BankCode: "COINS", Limit: "1-50000", Description: "Coins钱包"},
			{AccountType: "EWALLET", BankCode: "PAYMAYA", Limit: "1-50000", Description: "PayMaya钱包"},
			{AccountType: "EWALLET", BankCode: "GRABPAY", Limit: "1-50000", Description: "GrabPay钱包"},
			{AccountType: "EWALLET", BankCode: "SHOPEE", Limit: "1-50000", Description: "ShopeePay钱包"},
			{AccountType: "EWALLET", BankCode: "OMNIPAY", Limit: "1-50000", Description: "OmniPay钱包"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABP", Limit: "1-50000", Description: "AllBank Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "ALIP", Limit: "1-50000", Description: "Alipay Philippines Inc"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AUB", Limit: "1-50000", Description: "Asia United Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BDO", Limit: "1-50000", Description: "Banco de Oro"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BMB", Limit: "1-50000", Description: "Bangko Mabuhay"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BOC", Limit: "1-50000", Description: "Bank Of Commerce"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BPI", Limit: "1-50000", Description: "Bank of the Philippine Islands"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BPIDB", Limit: "1-50000", Description: "BPI Direct BanKO, Inc., A Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BRB", Limit: "1-50000", Description: "Binangonan Rural Bank (BRBDigital)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CBC", Limit: "1-50000", Description: "China Banking Corporation(China Bank)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CBS", Limit: "1-50000", Description: "China Bank Savings, Inc"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CCI", Limit: "1-50000", Description: "CIS BAYAD CENTER INC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CEBRUR", Limit: "1-50000", Description: "Cebuana Lhuillier Rural Bank, Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIMB", Limit: "1-50000", Description: "CIMB Bank Philippines, Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "CMG", Limit: "1-50000", Description: "CAMALIG BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CRB", Limit: "1-50000", Description: "COMMUNITY RURAL BANK OF ROMBLON, INC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CRD", Limit: "1-50000", Description: "CARD Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CSB", Limit: "1-50000", Description: "Citystate Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CSI", Limit: "1-50000", Description: "CARD SME BANK INC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CTBC", Limit: "1-50000", Description: "Ctbc Bank (Philippines) Corp."},
			{AccountType: "BANK_ACCOUNT", BankCode: "DBI", Limit: "1-50000", Description: "Dungganon Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DBP", Limit: "1-50000", Description: "Development Bank of the Philippines"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DCI", Limit: "1-50000", Description: "DUMAGUETE CITY DEVELOPMENT BANK, INC."},
			{AccountType: "BANK_ACCOUNT", BankCode: "DCP", Limit: "1-50000", Description: "DCPay Philippines Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "DOP", Limit: "1-50000", Description: "DEVT. BANK OF THE PHILIPPINES"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EQB", Limit: "1-50000", Description: "Equicom Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EWB", Limit: "1-50000", Description: "East-West Banking Corporation"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EWR", Limit: "1-50000", Description: "East West Rural Bank (Green Bank)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "GTB", Limit: "1-50000", Description: "GoTyme Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "IBI", Limit: "1-50000", Description: "ISLA Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ING", Limit: "1-50000", Description: "ING Bank N.V."},
			{AccountType: "BANK_ACCOUNT", BankCode: "JPM", Limit: "1-50000", Description: "JP Morgan Chase Bank, N.A."},
			{AccountType: "BANK_ACCOUNT", BankCode: "LBP", Limit: "1-50000", Description: "Land Bank of the Philippines"},
			{AccountType: "BANK_ACCOUNT", BankCode: "LSB", Limit: "1-50000", Description: "LEGAZPI SAVINGS BANK INC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "LUL", Limit: "1-50000", Description: "LULU FINANCIAL SERVICES (PHILS), INC."},
			{AccountType: "BANK_ACCOUNT", BankCode: "MBP", Limit: "1-50000", Description: "Maybank Philippines"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MCC", Limit: "1-50000", Description: "MINDANAO CONSOLIDATED COOPERATIVE"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MET", Limit: "1-50000", Description: "Metrobank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MSB", Limit: "1-50000", Description: "Malayan Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ONB", Limit: "1-50000", Description: "One Network Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "OWN", Limit: "1-50000", Description: "ownbank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PAP", Limit: "1-50000", Description: "PalawanPay"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PAR", Limit: "1-50000", Description: "Partner Rural Bank(Cotabato) Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "PBB", Limit: "1-50000", Description: "Philippine Business Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PBCOM", Limit: "1-50000", Description: "Philippine Bank of Communications"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PNB", Limit: "1-50000", Description: "Philippine National Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PNS", Limit: "1-50000", Description: "PNB Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PRB", Limit: "1-50000", Description: "Producers Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PSB", Limit: "1-50000", Description: "Philippine Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PTC", Limit: "1-50000", Description: "Philippine Trust Company"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PVB", Limit: "1-50000", Description: "Philippine Veterans Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "QCB", Limit: "1-50000", Description: "Queen City Development Bank, Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "QRB", Limit: "1-50000", Description: "Quezon Capital Rural Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RBG", Limit: "1-50000", Description: "RURAL BANK OF GUINOBATAN, INC."},
			{AccountType: "BANK_ACCOUNT", BankCode: "RCBC", Limit: "1-50000", Description: "Rizal Commercial Banking Corp. (RCBC)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RSB", Limit: "1-50000", Description: "Robinsons Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RSBI", Limit: "1-50000", Description: "Rcbc Savings Bank Inc."},
			{AccountType: "BANK_ACCOUNT", BankCode: "SBA", Limit: "1-50000", Description: "Sterling Bank Of Asia"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SBC", Limit: "1-50000", Description: "Security Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SEB", Limit: "1-50000", Description: "SEABANK PH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SPY", Limit: "1-50000", Description: "Starpay Corporation"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SSB", Limit: "1-50000", Description: "Sun Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TSB", Limit: "1-50000", Description: "THE STANDARD CHARTERED BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TYC", Limit: "1-50000", Description: "Tayocash"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UBP", Limit: "1-50000", Description: "Union Bank Of The Philippines"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UCBSB", Limit: "1-50000", Description: "UCBP Savings bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UCPB", Limit: "1-50000", Description: "United Coconut Planters Bank (UCPB)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "USS", Limit: "1-50000", Description: "USSC Money Services"},
			{AccountType: "BANK_ACCOUNT", BankCode: "WDB", Limit: "1-50000", Description: "Wealth Development Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "YUANSB", Limit: "1-50000", Description: "Yuanta Savings Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ZTI", Limit: "1-50000", Description: "ZYBI TECH, INC."},
		},
	},
	{
		CountryCode: "TH",
		Currency:    "THB",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "BANK_ACCOUNT", BankCode: "BAAC", Limit: "1-8000", Description: "BAAC ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BAY", Limit: "1-8000", Description: "Bank of Ayudhya (Krungsri / กรุงศรี)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BBL", Limit: "1-8000", Description: "Bangkok Bank ธนาคารกรุงเทพ"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIMB", Limit: "1-8000", Description: "CIMB Thai ธนาคารซีไอเอ็มบีไทย"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CITI", Limit: "1-8000", Description: "Citibank N.A. ซิตี้แบงก์ ประเทศไทย"},
			{AccountType: "BANK_ACCOUNT", BankCode: "GHB", Limit: "1-8000", Description: "GHB ธนาคารอาคารสงเคราะห์"},
			{AccountType: "BANK_ACCOUNT", BankCode: "GSB", Limit: "1-8000", Description: "GSB ธนาคารออมสิน"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HSBC", Limit: "1-8000", Description: "HSBC เอชเอสบีซี"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ICBC", Limit: "1-8000", Description: "ICBC(Thai) ธนาคารไอซีบีซี(ประเทศไทย)จำกัด(มหาชน)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "IBANK", Limit: "1-8000", Description: "Islamic Bank ธนาคารอิสลามแห่งประเทศไทย"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KBANK", Limit: "1-8000", Description: "Kasikorn Bank ธนาคารกสิกรไทย"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KKP", Limit: "1-8000", Description: "Kiatnakin Phatra Bank ธนาคารเกียรตินาคินภัทร"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KTB", Limit: "1-8000", Description: "KTB ธนาคารกรุงไทย"},
			{AccountType: "BANK_ACCOUNT", BankCode: "LHB", Limit: "1-8000", Description: "Land and Houses Bank ธนาคารแลนด์ แอนด์ เฮ้าส์"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCB", Limit: "1-8000", Description: "SCB ธนาคารไทยพาณิชย์"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCBT", Limit: "1-8000", Description: "SCBT สแตนดาร์ดชาร์เตอร์ด"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TBANK", Limit: "1-8000", Description: "TBank ธนาคารธนชาต จำกัด (มหาชน)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TISCO", Limit: "1-8000", Description: "TISCO ธนาคารทิสโก้ จำกัด (มหาชน)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TMB", Limit: "1-8000", Description: "TTB ธนาคารทีเอ็มบีธนชาต จำกัด (มหาชน)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UOB", Limit: "1-8000", Description: "UOB ธนาคารยูโอบี จำกัด (มหาชน)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABN", Limit: "1-8000", Description: "ABN AMRO ธนาคารเอบีเอ็น แอมโร เอ็น.วี."},
			{AccountType: "BANK_ACCOUNT", BankCode: "MHCB", Limit: "1-8000", Description: "Mizuho ธนาคารมิสึโฮ คอร์ปอเรต จำกัด"},
		},
	},
	{
		CountryCode: "VN",
		Currency:    "VND",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "BANK_ACCOUNT", BankCode: "VCB", Limit: "10000-50000000", Description: "Vietcombank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DAB", Limit: "10000-50000000", Description: "DongA Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TCB", Limit: "10000-50000000", Description: "Techcombank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MB", Limit: "10000-50000000", Description: "Military Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "VIB", Limit: "10000-50000000", Description: "Vietnam International Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ICB", Limit: "10000-50000000", Description: "VietinBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EXB", Limit: "10000-50000000", Description: "Eximbank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ACB", Limit: "10000-50000000", Description: "Asia Commercial Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HDB", Limit: "10000-50000000", Description: "HDBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MSB", Limit: "10000-50000000", Description: "Maritime Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NCB", Limit: "10000-50000000", Description: "National Citizen Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "VAB", Limit: "10000-50000000", Description: "Viet A Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "VPB", Limit: "10000-50000000", Description: "VPBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "STB", Limit: "10000-50000000", Description: "Sacombank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BAB", Limit: "10000-50000000", Description: "Bac A Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "GPB", Limit: "10000-50000000", Description: "GPBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AGB", Limit: "10000-50000000", Description: "Agribank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BIDV", Limit: "10000-50000000", Description: "BIDV"},
			{AccountType: "BANK_ACCOUNT", BankCode: "OJB", Limit: "10000-50000000", Description: "OceanBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PGB", Limit: "10000-50000000", Description: "PG Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SHB", Limit: "10000-50000000", Description: "Saigon - Hanoi Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "TPB", Limit: "10000-50000000", Description: "TienPhong Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NAB", Limit: "10000-50000000", Description: "Nam A Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SGB", Limit: "10000-50000000", Description: "Saigon Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABB", Limit: "10000-50000000", Description: "An Binh Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCB", Limit: "10000-50000000", Description: "Saigon Commercial Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "IVB", Limit: "10000-50000000", Description: "Indovina Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "VCCB", Limit: "10000-50000000", Description: "Viet Capital Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "OCB", Limit: "10000-50000000", Description: "Orient Commercial Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SEA", Limit: "10000-50000000", Description: "Dong Nam A Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "LVB", Limit: "10000-50000000", Description: "LienVietPostBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "WRB", Limit: "10000-50000000", Description: "Woori Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PVCOMBANK", Limit: "10000-50000000", Description: "PVcomBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SHNB", Limit: "10000-50000000", Description: "Shinhan Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KLB", Limit: "10000-50000000", Description: "Kien Long Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BVB", Limit: "10000-50000000", Description: "BaoViet Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "GAB", Limit: "10000-50000000", Description: "Dai A Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NVB", Limit: "10000-50000000", Description: "Navibank"},
		},
	},
	{
		CountryCode: "ID",
		Currency:    "IDR",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "DANA", Limit: "10000-20000000", Description: "Dana钱包"},
			{AccountType: "EWALLET", BankCode: "OVO", Limit: "10000-20000000", Description: "OVO钱包"},
			{AccountType: "EWALLET", BankCode: "GOPAY", Limit: "10000-20000000", Description: "GoPay钱包"},
			{AccountType: "EWALLET", BankCode: "LINKAJA", Limit: "10000-20000000", Description: "LinkAja钱包"},
			{AccountType: "EWALLET", BankCode: "SHOPEEPAY", Limit: "10000-20000000", Description: "ShopeePay钱包"},
			{AccountType: "BANK_ACCOUNT", BankCode: "002", Limit: "10000-50000000", Description: "BRI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "008", Limit: "10000-50000000", Description: "MANDIRI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "009", Limit: "10000-50000000", Description: "BNI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "011", Limit: "10000-50000000", Description: "BANK DANAMON"},
			{AccountType: "BANK_ACCOUNT", BankCode: "013", Limit: "10000-50000000", Description: "PERMATA/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "014", Limit: "10000-50000000", Description: "BCA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "016", Limit: "10000-50000000", Description: "MAYBANK INDONESIA/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "019", Limit: "10000-50000000", Description: "BANK PAN INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "022", Limit: "10000-50000000", Description: "CIMB NIAGA/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "023", Limit: "10000-50000000", Description: "UOB INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "028", Limit: "10000-50000000", Description: "OCBC NISP/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "031", Limit: "10000-50000000", Description: "CITIBANK NA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "033", Limit: "10000-50000000", Description: "BANK OF AMERICA NA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "036", Limit: "10000-50000000", Description: "BANK CHINA CONSTRUCTION"},
			{AccountType: "BANK_ACCOUNT", BankCode: "037", Limit: "10000-50000000", Description: "BANK ARTHA GRAHA INTERNASIONAL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "041", Limit: "10000-50000000", Description: "PT. BANK HSBC INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "042", Limit: "10000-50000000", Description: "MUFG BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "046", Limit: "10000-50000000", Description: "DBS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "047", Limit: "10000-50000000", Description: "BANK RESONA PERDANIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "050", Limit: "10000-50000000", Description: "STANDARD CHARTERED BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "054", Limit: "10000-50000000", Description: "BANK CAPITAL INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "068", Limit: "10000-50000000", Description: "PT BANK WOORI SAUDARA INDONESIA 1906"},
			{AccountType: "BANK_ACCOUNT", BankCode: "069", Limit: "10000-50000000", Description: "BANK OF CHINA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "076", Limit: "10000-50000000", Description: "BANK BUMI ARTA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "097", Limit: "10000-50000000", Description: "BANK MAYAPADA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "110", Limit: "10000-50000000", Description: "BPD JABAR BANTEN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "111", Limit: "10000-50000000", Description: "BANK DKI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "112", Limit: "10000-50000000", Description: "BPD DIY"},
			{AccountType: "BANK_ACCOUNT", BankCode: "113", Limit: "10000-50000000", Description: "BPD JAWA TENGAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "114", Limit: "10000-50000000", Description: "BPD JAWA TIMUR/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "115", Limit: "10000-50000000", Description: "BPD JAMBI/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "116", Limit: "10000-50000000", Description: "BANK ACEH SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "117", Limit: "10000-50000000", Description: "BPD SUMATERA UTARA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "118", Limit: "10000-50000000", Description: "BPD SUMATERA BARAT/NAGARI SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "119", Limit: "10000-50000000", Description: "BPD RIAU KEPRI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "120", Limit: "10000-50000000", Description: "BPD SUMSEL BABEL/SYR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "122", Limit: "10000-50000000", Description: "BPD KALIMANTAN SELATAN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "123", Limit: "10000-50000000", Description: "BPD KALIMANTAN BARAT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "124", Limit: "10000-50000000", Description: "BPD KALTIM KALTARA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "125", Limit: "10000-50000000", Description: "BPD KALIMANTAN TENGAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "126", Limit: "10000-50000000", Description: "BPD SULSEL BAR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "127", Limit: "10000-50000000", Description: "BPD SULAWESI UTARA DAN GORONTALO"},
			{AccountType: "BANK_ACCOUNT", BankCode: "128", Limit: "10000-50000000", Description: "BPD NUSA TENGGARA BARAT SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "129", Limit: "10000-50000000", Description: "BPD BALI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "130", Limit: "10000-50000000", Description: "BPD NTT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "131", Limit: "10000-50000000", Description: "BPD MALUKU DAN MALUKU UTARA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "132", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH PAPUA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "133", Limit: "10000-50000000", Description: "BPD BENGKULU"},
			{AccountType: "BANK_ACCOUNT", BankCode: "135", Limit: "10000-50000000", Description: "BPD SULAWESI TENGGARA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "137", Limit: "10000-50000000", Description: "BPD BANTEN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "147", Limit: "10000-50000000", Description: "BANK MUAMALAT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "151", Limit: "10000-50000000", Description: "MESTIKA DHARMA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "153", Limit: "10000-50000000", Description: "SINARMAS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "157", Limit: "10000-50000000", Description: "MASPION"},
			{AccountType: "BANK_ACCOUNT", BankCode: "161", Limit: "10000-50000000", Description: "GANESHA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "164", Limit: "10000-50000000", Description: "BANK ICBC INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "167", Limit: "10000-50000000", Description: "BANK QNB INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "200", Limit: "10000-50000000", Description: "BTN/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "213", Limit: "10000-50000000", Description: "BANK BTPN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "425", Limit: "10000-50000000", Description: "BPD JABAR BANTEN SYR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "426", Limit: "10000-50000000", Description: "MEGA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "451", Limit: "10000-50000000", Description: "BANK SYARIAH INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "472", Limit: "10000-50000000", Description: "BANK JASA JAKARTA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "484", Limit: "10000-50000000", Description: "PT BANK KEB HANA INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "485", Limit: "10000-50000000", Description: "MNC BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "490", Limit: "10000-50000000", Description: "NEO COMMERCE"},
			{AccountType: "BANK_ACCOUNT", BankCode: "494", Limit: "10000-50000000", Description: "BANK RAYA INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "501", Limit: "10000-50000000", Description: "BCA Digital"},
			{AccountType: "BANK_ACCOUNT", BankCode: "503", Limit: "10000-50000000", Description: "NATIONALNOBU"},
			{AccountType: "BANK_ACCOUNT", BankCode: "506", Limit: "10000-50000000", Description: "BANK MEGA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "513", Limit: "10000-50000000", Description: "BANK INA PERDANA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "523", Limit: "10000-50000000", Description: "PT BANK SAHABAT SAMPOERNA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "535", Limit: "10000-50000000", Description: "SEABANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "536", Limit: "10000-50000000", Description: "BCA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "542", Limit: "10000-50000000", Description: "BANK JAGO/SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "547", Limit: "10000-50000000", Description: "BANK BTPN SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "548", Limit: "10000-50000000", Description: "BANK MULTI ARTA SENTOSA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "553", Limit: "10000-50000000", Description: "BANK MAYORA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "555", Limit: "10000-50000000", Description: "BANK INDEX SELINDO"},
			{AccountType: "BANK_ACCOUNT", BankCode: "564", Limit: "10000-50000000", Description: "PT BANK MANDIRI TASPEN POS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "566", Limit: "10000-50000000", Description: "BANK VICTORIA INTERNASIONAL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "567", Limit: "10000-50000000", Description: "ALLO BANK INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "722", Limit: "10000-50000000", Description: "BANK DANAMON SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "724", Limit: "10000-50000000", Description: "BANK DKI SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "725", Limit: "10000-50000000", Description: "BPD JAWA TENGAH SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "727", Limit: "10000-50000000", Description: "BPD KALIMANTAN BARAT SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "728", Limit: "10000-50000000", Description: "BPD KALIMANTAN SELATAN SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "729", Limit: "10000-50000000", Description: "BPD KALTIM KALTARA SYR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "733", Limit: "10000-50000000", Description: "BPD SUMATERA UTARA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "734", Limit: "10000-50000000", Description: "SINARMAS SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "735", Limit: "10000-50000000", Description: "BPD SULSEL BAR SYR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "736", Limit: "10000-50000000", Description: "BPD DIY SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "945", Limit: "10000-50000000", Description: "BANK IBK INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "947", Limit: "10000-50000000", Description: "BANK ALADIN SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "949", Limit: "10000-50000000", Description: "BANK CTBC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "VICTORIA_SYAR", Limit: "10000-50000000", Description: "PT. BANK VICTORIA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "VICTORIA", Limit: "10000-50000000", Description: "PT. BANK VICTORIA INTERNATIONAL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SUMUT_SYAR", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH SUMUT UUS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SUMUT", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH SUMUT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SUMSEL_BABEL_SYAR", Limit: "10000-50000000", Description: "PT. BPD SUMSEL DAN BABEL UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SUMSEL_BABEL", Limit: "10000-50000000", Description: "PT. BPD SUMSEL DAN BABEL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SUMITOMO", Limit: "10000-50000000", Description: "PT. BANK SUMITOMO MITSUI INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SULUT", Limit: "10000-50000000", Description: "PT. BANK SULUTGO"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SULTENG", Limit: "10000-50000000", Description: "PT. BPD SULAWESI TENGAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SULSELBAR_SYAR", Limit: "10000-50000000", Description: "PT. BANK SULSELBAR UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SULSELBAR", Limit: "10000-50000000", Description: "PT. BANK SULSELBAR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SHINHAN", Limit: "10000-50000000", Description: "PT. BANK SHINHAN INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SBI", Limit: "10000-50000000", Description: "PT. BANK SBI INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RIAU_SYAR", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH RIAU KEPRI SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RIAU", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH RIAU KEPRI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RBOS", Limit: "10000-50000000", Description: "THE ROYAL BANK OF SCOTLAND N.V."},
			{AccountType: "BANK_ACCOUNT", BankCode: "RABOBANK", Limit: "10000-50000000", Description: "PT. BANK RABOBANK INTERNATIONAL INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PURBA", Limit: "10000-50000000", Description: "PT. BANK PURBA DANARTA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PUNDI", Limit: "10000-50000000", Description: "PT. BANK PUNDI INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PRIMA_MASTER", Limit: "10000-50000000", Description: "PT. PRIMA MASTER BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PERMATA_VA", Limit: "10000-50000000", Description: "PT. BANK PERMATA TBK. - VIRTUAL ACCOUNT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PERMATA", Limit: "10000-50000000", Description: "PT. BANK PERMATA TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "PANIN_SYAR", Limit: "10000-50000000", Description: "PT. BANK PANIN SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "OK", Limit: "10000-50000000", Description: "PT. BANK OKE INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "OCBC", Limit: "10000-50000000", Description: "PT. BANK OCBC NISP TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "NTT", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH NTT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NTB", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH NTB"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NAGARI_SYAR", Limit: "10000-50000000", Description: "PT. BANK NAGARI UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NAGARI", Limit: "10000-50000000", Description: "PT. BANK NAGARI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NIAGA_SYAR", Limit: "10000-50000000", Description: "PT. BANK NIAGA TBK. SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MUTIARA", Limit: "10000-50000000", Description: "PT. BANK JTRUST INDONESIA, TBK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MIZUHO", Limit: "10000-50000000", Description: "PT. BANK MIZUHO INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MITRANIAGA", Limit: "10000-50000000", Description: "PT. BANK MITRANIAGA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "METRO", Limit: "10000-50000000", Description: "PT. BANK METRO EXPRESS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MAYBANK_UUS", Limit: "10000-50000000", Description: "PT. BANK MAYBANK INDONESIA TBK. UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MAYBANK", Limit: "10000-50000000", Description: "PT. BANK MAYBANK INDONESIA TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "MANDIRI_TASPEN", Limit: "10000-50000000", Description: "PT. BANK MANDIRI TASPEN POS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MALUKU", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH MALUKU"},
			{AccountType: "BANK_ACCOUNT", BankCode: "LAMPUNG", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH LAMPUNG"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KALTIM_SYAR", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH KALTIM - UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KALTIM", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH KALTIM"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KALSEL_SYAR", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH KALSEL - UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KALSEL", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH KALSEL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KALBAR_SYAR", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH KALBAR UUS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KALBAR", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH KALBAR"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JTRUST", Limit: "10000-50000000", Description: "PT. BANK JTRUST INDONESIA TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "JATIM_SYAR", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH JATIM - UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JATIM", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH JATIM"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JATENG_SYAR", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH JAWA TENGAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JATENG", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH JAWA TENGAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JAMBI", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH JAMBI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JAGO", Limit: "10000-50000000", Description: "PT. BANK JAGO TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "INDIA", Limit: "10000-50000000", Description: "PT. BANK OF INDIA INDONESIA TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "HS_1906", Limit: "10000-50000000", Description: "PT. BANK WOORI SAUDARA INDONESIA 1906,TBK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HANA", Limit: "10000-50000000", Description: "PT. BANK KEB HANA INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FAMA", Limit: "10000-50000000", Description: "PT. BANK FAMA INTERNATIONAL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EKONOMI", Limit: "10000-50000000", Description: "PT. BANK EKONOMI RAHARJA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DKI_SYAR", Limit: "10000-50000000", Description: "PT. BANK DKI UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DIY_SYAR", Limit: "10000-50000000", Description: "PT.BANK PEMBANGUNAN DAERAH DIY UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DIY", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH DIY"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DIPO", Limit: "10000-50000000", Description: "PT. BANK DIPO INTERNATIONAL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DEUTSCHE", Limit: "10000-50000000", Description: "DEUTSCHE BANK AG."},
			{AccountType: "BANK_ACCOUNT", BankCode: "DANAMON_SYAR", Limit: "10000-50000000", Description: "PT. BANK DANAMON INDONESIA UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "COMMONWEALTH", Limit: "10000-50000000", Description: "PT. BANK OCBC NISP, Tbk."},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIMB_VA", Limit: "10000-50000000", Description: "PT. BANK CIMB NIAGA TBK. - VIRTUAL ACCOUNT."},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIMB_REKENING_PONSEL", Limit: "10000-50000000", Description: "PT. BANK CIMB NIAGA TBK. - REKENING PONSEL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIMB", Limit: "10000-50000000", Description: "PT. BANK CIMB NIAGA TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "CHASE", Limit: "10000-50000000", Description: "JP MORGAN CHASE BANK, N.A"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CENTRATAMA", Limit: "10000-50000000", Description: "PT. CENTRATAMA NASIONAL BANK"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BUMIPUTERA", Limit: "10000-50000000", Description: "PT. BANK BUMIPUTERA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BUKOPIN_SYAR", Limit: "10000-50000000", Description: "PT. BANK SYARIAH BUKOPIN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BUKOPIN", Limit: "10000-50000000", Description: "PT BANK KB BUKOPIN TBK."},
			{AccountType: "BANK_ACCOUNT", BankCode: "BTPN_SYAR", Limit: "10000-50000000", Description: "PT. BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BTPN", Limit: "10000-50000000", Description: "PT. BANK SMBC Indonesia Tbk"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BTN_SYAR", Limit: "10000-50000000", Description: "PT. BANK TABUNGAN NEGARA (PERSERO) UNIT USAHA SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BTN", Limit: "10000-50000000", Description: "PT. BANK TABUNGAN NEGARA (PERSERO)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BRI_VA", Limit: "10000-50000000", Description: "PT. BANK RAKYAT INDONESIA (PERSERO) - VIRTUAL ACCOUNT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BNP_PARIBAS", Limit: "10000-50000000", Description: "PT. BANK BNP PARIBAS INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BNP", Limit: "10000-50000000", Description: "PT. BANK NUSANTARA PARAHYANGAN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BISNIS", Limit: "10000-50000000", Description: "PT. BANK BISNIS INTERNASIONAL"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BCA_VA", Limit: "10000-50000000", Description: "PT. BANK CENTRAL ASIA TBK. - VIRTUAL ACCOUNT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BARCLAYS", Limit: "10000-50000000", Description: "PT BANK BARCLAYS INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BANTEN", Limit: "10000-50000000", Description: "PT. BANK BANTEN"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BANGKOK", Limit: "10000-50000000", Description: "BANGKOK BANK PUBLIC CO.LTD"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BALI", Limit: "10000-50000000", Description: "PT. BANK PEMBANGUNAN DAERAH BALI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ARTAJASA", Limit: "10000-50000000", Description: "PT. ARTAJASA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ANZ", Limit: "10000-50000000", Description: "PT. BANK ANZ INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ANTAR_DAERAH", Limit: "10000-50000000", Description: "PT. BANK ANTAR DAERAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ANGLOMAS", Limit: "10000-50000000", Description: "PT. BANK AMAR INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ANDARA", Limit: "10000-50000000", Description: "PT. BANK ANDARA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AMAR", Limit: "10000-50000000", Description: "PT. BANK AMAR INDONESIA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ACEH_SYAR", Limit: "10000-50000000", Description: "PT. BPD ISTIMEWA ACEH SYARIAH"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ACEH", Limit: "10000-50000000", Description: "PT. BANK ACEH"},
		},
	},
	{
		CountryCode: "MY",
		Currency:    "MYR",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "TNG", Limit: "10-50000", Description: "Touch 'n Go eWallet"},
			{AccountType: "EWALLET", BankCode: "BIGPAY", Limit: "10-50000", Description: "BigPay"},
			{AccountType: "EWALLET", BankCode: "FINEXUS", Limit: "10-50000", Description: "FINEXUS"},
			{AccountType: "EWALLET", BankCode: "BOOST", Limit: "10-50000", Description: "BOOST"},
			{AccountType: "EWALLET", BankCode: "SHOPEE", Limit: "10-50000", Description: "SHOPEE"},
			{AccountType: "EWALLET", BankCode: "GXB", Limit: "10-50000", Description: "GXB"},
			{AccountType: "EWALLET", BankCode: "MASB", Limit: "10-50000", Description: "MASB"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BIMB", Limit: "10-50000", Description: "Bank Islam"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIMB", Limit: "10-50000", Description: "CIMB Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UOB", Limit: "10-50000", Description: "United Oversea Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MBB", Limit: "10-50000", Description: "Maybank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HSBC", Limit: "10-50000", Description: "HSBC Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "RHB", Limit: "10-50000", Description: "RHB Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "OCBC", Limit: "10-50000", Description: "OCBC Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PBB", Limit: "10-50000", Description: "Public Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCB", Limit: "10-50000", Description: "Standard Chartered"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AMB", Limit: "10-50000", Description: "AmBank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BKRM", Limit: "10-50000", Description: "Bank Kerjasama Rakyat"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BSN", Limit: "10-50000", Description: "Bank Simpanan Nasional"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AFB", Limit: "10-50000", Description: "Affin Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HLB", Limit: "10-50000", Description: "Hong Leong Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ALB", Limit: "10-50000", Description: "Alliance Bank"},
		},
	},
	{
		CountryCode: "PK",
		Currency:    "PKR",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "ALFA", Limit: "10-100000", Description: "ALFA钱包"},
			{AccountType: "EWALLET", BankCode: "BAFL", Limit: "10-100000", Description: "Bank Alfalah Limited"},
			{AccountType: "EWALLET", BankCode: "EASYPAISA", Limit: "10-100000", Description: "EasyPaisa钱包"},
			{AccountType: "EWALLET", BankCode: "JAZZCASH", Limit: "10-100000", Description: "JazzCash钱包"},
			{AccountType: "EWALLET", BankCode: "HBL_KONNECT", Limit: "10-100000", Description: "HBL KONNECT钱包"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABBL", Limit: "10-100000", Description: "Al Baraka Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABHI", Limit: "10-100000", Description: "Abhi Finance"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABL", Limit: "10-100000", Description: "Allied Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ACBL", Limit: "10-100000", Description: "Askari Commercial Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ADVANS", Limit: "10-100000", Description: "Advans Pakistan"},
			{AccountType: "BANK_ACCOUNT", BankCode: "APNA", Limit: "10-100000", Description: "Apna Microfinance Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BAHL", Limit: "10-100000", Description: "Bank AL Habib Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BARWAQT", Limit: "10-100000", Description: "Barwaqt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BIPL", Limit: "10-100000", Description: "BankIslami Pakistan"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BOK", Limit: "10-100000", Description: "Bank of Khyber"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BOP", Limit: "10-100000", Description: "Bank of Punjab"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BYKEA", Limit: "10-100000", Description: "BYKEA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CDNS", Limit: "10-100000", Description: "CDNS"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CITI", Limit: "10-100000", Description: "Citi Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "DIBPL", Limit: "10-100000", Description: "Dubai Islamic Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FAYSAL", Limit: "10-100000", Description: "Faysal Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FINCA", Limit: "10-100000", Description: "FINCA Microfinance Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FINJA", Limit: "10-100000", Description: "FINJA EMI"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FMB", Limit: "10-100000", Description: "First Microfinance Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FWBL", Limit: "10-100000", Description: "First Women Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HBL", Limit: "10-100000", Description: "Habib Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HBLASSET", Limit: "10-100000", Description: "HBL ASSET MANAGEMENT"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HMBL", Limit: "10-100000", Description: "Habib Metropolitan Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ICBC", Limit: "10-100000", Description: "ICBC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "JSB", Limit: "10-100000", Description: "JS Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "KHUSHALI", Limit: "10-100000", Description: "Khushali Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MCB", Limit: "10-100000", Description: "MCB Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MCBARIF", Limit: "10-100000", Description: "MCB ARIF HABIB"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MCIB", Limit: "10-100000", Description: "MCB Islamic Banking"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MEEZAN", Limit: "10-100000", Description: "Meezan Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MOD", Limit: "10-100000", Description: "MOD"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NAYAPAY", Limit: "10-100000", Description: "NayaPay Private Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NBP", Limit: "10-100000", Description: "National Bank of Pakistan"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NBPF", Limit: "10-100000", Description: "NBP Funds"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NRSP", Limit: "10-100000", Description: "NRSP Microfinance"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PAYMAX", Limit: "10-100000", Description: "PayMax (Zong)"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SADAPAY", Limit: "10-100000", Description: "SadaPay"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SAMBA", Limit: "10-100000", Description: "SAMBA"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCB", Limit: "10-100000", Description: "Standard Chartered Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SILK", Limit: "10-100000", Description: "Silk Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SIMPAISA", Limit: "10-100000", Description: "SimPaisa"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SINDH", Limit: "10-100000", Description: "Sindh Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SME", Limit: "10-100000", Description: "SME Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SONERI", Limit: "10-100000", Description: "Soneri Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SUMMIT", Limit: "10-100000", Description: "Summit Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UBANK", Limit: "10-100000", Description: "Ubank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UBL", Limit: "10-100000", Description: "United Bank Limited"},
			{AccountType: "BANK_ACCOUNT", BankCode: "WHITE", Limit: "10-100000", Description: "WHITE LABEL ATM"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ZARAI", Limit: "10-100000", Description: "Zarai Taraqiati Bank"},
		},
	},
	{
		CountryCode: "BD",
		Currency:    "BDT",
		Region:      HaiPayPayoutRegionAsia,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "BDT_BKASH", Limit: "100-50000", Description: "bkash"},
			{AccountType: "EWALLET", BankCode: "BDT_NAGAD", Limit: "100-50000", Description: "nagad"},
		},
	},
	{
		CountryCode: "EG",
		Currency:    "EGP",
		Region:      HaiPayPayoutRegionMiddleEast,
		Methods: []HaiPayPayoutMethod{
			{AccountType: "EWALLET", BankCode: "MEEZA", Limit: "20-30000", Description: "MeezaWallet 为埃及 Meeza 网络下的手机号电子钱包，支持根据号码识别账户类型，并向 Vodafone Cash、Orange Money、Etisalat Cash 等本地钱包进行代付。"},
			{AccountType: "EWALLET", BankCode: "OPAY", Limit: "20-30000", Description: "OpayCard"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABP", Limit: "20-30000", Description: "AllBank Inc"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AAIB", Limit: "20-30000", Description: "Arab African International Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABC", Limit: "20-30000", Description: "Arab Banking Corporation - Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABK", Limit: "20-30000", Description: "Al Ahli Bank of Kuwait – Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ABRK", Limit: "20-30000", Description: "Al Baraka Bank Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ADIB", Limit: "20-30000", Description: "Abu Dhabi Islamic Bank – Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AIB", Limit: "20-30000", Description: "Arab Investment Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ARAB", Limit: "20-30000", Description: "Arab Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ARIB", Limit: "20-30000", Description: "Arab International Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AUB", Limit: "20-30000", Description: "Ahly United Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "AUDI", Limit: "20-30000", Description: "Audi Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BBE", Limit: "20-30000", Description: "ATTIJARIWAFA BANK EGYPT S.A.E"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BDC", Limit: "20-30000", Description: "Banque Du Caire"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BLOM", Limit: "20-30000", Description: "Blom Bank Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "BOA", Limit: "20-30000", Description: "Bank of Alexandria"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CAE", Limit: "20-30000", Description: "Credit Agricole"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CIB", Limit: "20-30000", Description: "Commercial International Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "CITI", Limit: "20-30000", Description: "Citibank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EALB", Limit: "20-30000", Description: "Egyptian Arab Land Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EDBE", Limit: "20-30000", Description: "Export Development Bank of Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "EGB", Limit: "20-30000", Description: "Egyptian Gulf Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "ENBD", Limit: "20-30000", Description: "Emirates National Bank of Dubai"},
			{AccountType: "BANK_ACCOUNT", BankCode: "FAIB", Limit: "20-30000", Description: "Faisal Islamic Bank of Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HDB", Limit: "20-30000", Description: "Housing And Development Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "HSBC", Limit: "20-30000", Description: "HSBC"},
			{AccountType: "BANK_ACCOUNT", BankCode: "IDBE", Limit: "20-30000", Description: "Industrial Development Bank of Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MASH", Limit: "20-30000", Description: "Mashreq Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MIDB", Limit: "20-30000", Description: "Misr Iran Development Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "MISR", Limit: "20-30000", Description: "Banque Misr"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NBAD", Limit: "20-30000", Description: "National Bank of Abu Dhabi"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NBE", Limit: "20-30000", Description: "National Bank of Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NBG", Limit: "20-30000", Description: "National Bank of Greece"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NBK", Limit: "20-30000", Description: "National Bank of Kuwait – Egypt"},
			{AccountType: "BANK_ACCOUNT", BankCode: "NSB", Limit: "20-30000", Description: "Nasser Social Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "PDAC", Limit: "20-30000", Description: "The Principal Bank for Development and Agri."},
			{AccountType: "BANK_ACCOUNT", BankCode: "QNB", Limit: "20-30000", Description: "Qatar National Bank Alahli"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SAIB", Limit: "20-30000", Description: "Societe Arabe Internationale De Banque"},
			{AccountType: "BANK_ACCOUNT", BankCode: "SCB", Limit: "20-30000", Description: "Suez Canal Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UB", Limit: "20-30000", Description: "The United Bank"},
			{AccountType: "BANK_ACCOUNT", BankCode: "UNB", Limit: "20-30000", Description: "United National Bank"},
		},
	},
}
