import type {RouteRecordRaw} from 'vue-router'

/** views/operation */
export const operationRoutes: RouteRecordRaw = {
    path: '/operation',
    meta: {title: '运营管理', icon: 'Stamp'},
    redirect: '/operation/banner/banner-list',
    children: [
        {
            path: 'banner/banner-list',
            name: 'BannerManagement',
            component: () => import('@/views/operation/banner/banner-list.vue'),
            meta: {title: '首页Banner', parentTitle: '基础配置'},
        },
        {
            path: 'activity-message/activity-message-list',
            name: 'ActivityMessageManagement',
            component: () => import('@/views/operation/activity-message/activity-message-list.vue'),
            meta: {title: '活动消息', parentTitle: '活动管理'},
        },
        {
            path: 'guild/guild-list',
            name: 'GuildManagement',
            component: () => import('@/views/operation/guild/guild-list.vue'),
            meta: {title: '工会管理'},
        },
        {
            path: 'guild/guild-transfer-info/:guildId',
            name: 'GuildTransferInfoEdit',
            component: () => import('@/views/operation/guild/guild-transfer-info-edit.vue'),
            meta: {
                title: '编辑转账信息',
                hidden: true,
                parentPermission: ['GuildManagement', 'GuildTransferManagement', 'CoinMerchantGuildTransferManagement'],
            },
        },
        {
            path: 'guild/guild-transfer-list',
            name: 'GuildTransferManagement',
            component: () => import('@/views/operation/guild/guild-transfer-list.vue'),
            meta: {title: '普通工会代付'},
        },
        {
            path: 'guild/coin-merchant-guild-transfer-list',
            name: 'CoinMerchantGuildTransferManagement',
            component: () => import('@/views/operation/guild/guild-transfer-list.vue'),
            meta: {title: '币商代付', parentTitle: '币商管理'},
        },
        {
            path: 'guild/coin-merchant-payout-detail-list',
            name: 'CoinMerchantPayoutDetailList',
            component: () => import('@/views/operation/salary/guild-payout-detail-list.vue'),
            meta: {title: '币商代付详情', parentTitle: '币商管理'},
        },
        {
            path: 'guild/guild-transfer-detail/:id',
            name: 'GuildTransferDetail',
            component: () => import('@/views/operation/guild/guild-transfer-detail.vue'),
            meta: {
                title: '工会结算详情',
                hidden: true,
                parentPermission: ['GuildTransferManagement', 'CoinMerchantGuildTransferManagement'],
            },
        },
        {
            path: 'guild/guild-cms-user-list',
            name: 'GuildCMSUserManagement',
            component: () => import('@/views/operation/guild/guild-cms-user-list.vue'),
            meta: {title: '工会CMS用户'},
        },
        {
            path: 'guild/guild-visibility-list',
            name: 'GuildVisibilityManagement',
            component: () => import('@/views/operation/guild/guild-visibility-list.vue'),
            meta: {title: '工会可见性'},
        },
        {
            path: 'guild/platform-anchor-visibility-list',
            name: 'PlatformAnchorVisibilityManagement',
            component: () => import('@/views/operation/guild/platform-anchor-visibility-list.vue'),
            meta: {title: '平台主播可见性'},
        },
        {
            path: 'guild/guild-anchor-daily-live-list',
            name: 'GuildAnchorDailyLiveManagement',
            component: () => import('@/views/operation/guild/guild-anchor-daily-live-list.vue'),
            meta: {title: '名下主播每日流水', parentTitle: '工会数据'},
        },
        {
            path: 'guild/guild-detail',
            name: 'GuildDetail',
            component: () => import('@/views/operation/guild/guild-detail.vue'),
            meta: {
                title: '工会详情',
                hidden: true,
                parentPermission: ['GuildManagement', 'GuildTransferManagement', 'CoinMerchantGuildTransferManagement', 'GuildProfileManagement', 'AnchorListManagement'],
            },
        },
        {
            path: 'guild/platform-anchor-list',
            name: 'PlatformAnchorList',
            component: () => import('@/views/operation/guild/platform-anchor-list.vue'),
            meta: {title: '平台主播'},
        },
        {
            path: 'guild/platform-anchor-transfer-info/:anchorId',
            name: 'PlatformAnchorTransferInfoEdit',
            component: () => import('@/views/operation/guild/guild-transfer-info-edit.vue'),
            meta: {
                title: '编辑平台主播转账信息',
                hidden: true,
                parentPermission: 'PlatformAnchorList',
            },
        },
        {
            path: 'guild/guild-recycle-bin',
            name: 'GuildRecycleBinManagement',
            component: () => import('@/views/operation/guild/guild-recycle-bin.vue'),
            meta: {title: '工会垃圾库'},
        },
        {
            path: 'guild/guild-anchor-import-result',
            name: 'GuildAnchorImportResult',
            component: () => import('@/views/operation/guild/guild-anchor-import-result.vue'),
            meta: {title: '工会主播导入结果', hidden: true, parentPermission: 'GuildManagement'},
        },
        {
            path: 'guild/guild-members',
            name: 'GuildMembers',
            component: () => import('@/views/operation/guild/guild-members.vue'),
            meta: {title: '工会成员', hidden: true, parentPermission: 'GuildManagement'},
        },
        {
            path: 'guild/guild-profile-members',
            name: 'GuildProfileMembers',
            component: () => import('@/views/operation/guild/guild-profile-members.vue'),
            meta: {title: '名下主播', hidden: true, parentPermission: 'GuildProfileManagement'},
        },
        {
            path: 'guild/guild-profile-anchor-daily-live',
            name: 'GuildProfileAnchorDailyLive',
            component: () => import('@/views/operation/guild/guild-profile-anchor-daily-live.vue'),
            meta: {title: '每日流水', hidden: true, parentPermission: 'GuildProfileManagement'},
        },
        {
            path: 'guild/guild-profile',
            name: 'GuildProfileManagement',
            component: () => import('@/views/operation/guild/guild-profile.vue'),
            meta: {title: '工会数据查询', parentTitle: '工会数据'},
        },
        {
            path: 'recharge/recharge-cfg-list',
            name: 'RechargeCfgManagement',
            component: () => import('@/views/operation/recharge/recharge-cfg-list.vue'),
            meta: {title: '充值配置', parentTitle: '用户管理'},
        },
        {
            path: 'recharge/coin-merchant-recharge-cfg-list',
            name: 'CoinMerchantRechargeCfgManagement',
            component: () => import('@/views/operation/recharge/coin-merchant-recharge-cfg-list.vue'),
            meta: {title: '币商充值档位'},
        },
        {
            path: 'vip/vip-cfg-list',
            name: 'VipCfgManagement',
            component: () => import('@/views/operation/vip/vip-cfg-list.vue'),
            meta: {title: 'VIP配置', parentTitle: '用户管理'},
        },
        {
            path: 'app-pkg/app-pkg-list',
            redirect: '/config/app-pkg-list',
        },
        {
            path: 'random-nickname/random-nickname-cfg',
            name: 'RandomNicknameManagement',
            component: () => import('@/views/operation/random-nickname/random-nickname-cfg.vue'),
            meta: {title: '随机昵称库', parentTitle: '基础配置'},
        },
        {
            path: 'customer-service/customer-service-cfg',
            name: 'CustomerServiceCfgManagement',
            component: () => import('@/views/operation/customer-service/customer-service-cfg.vue'),
            meta: {title: '客服联系配置', parentTitle: '主播与工会管理'},
        },
        {
            path: 'wallet/wallet-exchange-cfg',
            name: 'WalletExchangeCfgManagement',
            component: () => import('@/views/operation/wallet/wallet-exchange-cfg.vue'),
            meta: {title: '结算基础配置'},
        },
        {
            path: 'salary/effective-live-cfg',
            redirect: '/operation/wallet/wallet-exchange-cfg',
        },
        {
            path: 'recharge/payment-country-cfg',
            name: 'PaymentCountryCfgManagement',
            component: () => import('@/views/operation/recharge/payment-country-cfg.vue'),
            meta: {title: '普通用户代收支付配置', paymentCountryCfgScope: 'normal'},
        },
        {
            path: 'recharge/payment-country-cfg/:continent',
            name: 'PaymentCountryCfgContinent',
            component: () => import('@/views/operation/recharge/payment-country-continent.vue'),
            meta: {
                title: '普通用户国家/地区代收配置',
                hidden: true,
                parentPermission: ['PaymentCountryCfgManagement'],
                paymentCountryCfgScope: 'normal',
            },
        },
        {
            path: 'recharge/payment-country-cfg/:continent/:countryCode',
            name: 'PaymentCountryCfgEdit',
            component: () => import('@/views/operation/recharge/payment-country-edit.vue'),
            meta: {
                title: '普通用户代收配置编辑',
                hidden: true,
                parentPermission: ['PaymentCountryCfgManagement'],
                paymentCountryCfgScope: 'normal',
            },
        },
        {
            path: 'recharge/coin-merchant-payment-country-cfg',
            name: 'CoinMerchantPaymentCountryCfgManagement',
            component: () => import('@/views/operation/recharge/payment-country-cfg.vue'),
            meta: {title: '币商代收支付配置', paymentCountryCfgScope: 'coinMerchant'},
        },
        {
            path: 'recharge/coin-merchant-payment-country-cfg/:continent',
            name: 'CoinMerchantPaymentCountryCfgContinent',
            component: () => import('@/views/operation/recharge/payment-country-continent.vue'),
            meta: {
                title: '币商国家/地区代收配置',
                hidden: true,
                parentPermission: ['CoinMerchantPaymentCountryCfgManagement'],
                paymentCountryCfgScope: 'coinMerchant',
            },
        },
        {
            path: 'recharge/coin-merchant-payment-country-cfg/:continent/:countryCode',
            name: 'CoinMerchantPaymentCountryCfgEdit',
            component: () => import('@/views/operation/recharge/payment-country-edit.vue'),
            meta: {
                title: '币商代收配置编辑',
                hidden: true,
                parentPermission: ['CoinMerchantPaymentCountryCfgManagement'],
                paymentCountryCfgScope: 'coinMerchant',
            },
        },
        {
            path: 'salary/anchor-salary-cfg-list',
            name: 'AnchorSalaryCfgManagement',
            component: () => import('@/views/operation/salary/anchor-salary-cfg-list.vue'),
            meta: {title: '主播结算薪资'},
        },
        {
            path: 'salary/anchor-salary-social-share-cfg-list',
            name: 'AnchorSalarySocialShareCfgManagement',
            component: () => import('@/views/operation/salary/anchor-salary-social-share-cfg-list.vue'),
            meta: {title: '有底薪社交流水分佣配置'},
        },
        {
            path: 'salary/anchor-no-salary-share-cfg',
            name: 'AnchorNoSalaryShareCfgManagement',
            component: () => import('@/views/operation/salary/anchor-no-salary-share-cfg.vue'),
            meta: {title: '无底薪社交流水分佣配置'},
        },
        {
            path: 'salary/anchor-salary-game-share-cfg-list',
            name: 'AnchorSalaryGameShareCfgManagement',
            component: () => import('@/views/operation/salary/anchor-game-share-cfg-list.vue'),
            props: {salaryType: 1},
            meta: {title: '有底薪游戏流水档位分佣配置'},
        },
        {
            path: 'salary/anchor-no-salary-game-share-cfg-list',
            name: 'AnchorNoSalaryGameShareCfgManagement',
            component: () => import('@/views/operation/salary/anchor-game-share-cfg-list.vue'),
            props: {salaryType: 2},
            meta: {title: '无底薪游戏流水档位分佣配置'},
        },
        {
            path: 'salary/anchor-income-settlement-log-list',
            name: 'AnchorIncomeSettlementLogList',
            component: () => import('@/views/operation/salary/anchor-income-settlement-log-list.vue'),
            meta: {title: '主播结算流水'},
        },
        {
            path: 'salary/platform-anchor-payout-list',
            name: 'PlatformAnchorPayoutList',
            component: () => import('@/views/operation/salary/platform-anchor-payout-list.vue'),
            meta: {title: '平台主播代付'},
        },
        {
            path: 'salary/guild-income-settlement-log-list',
            name: 'GuildIncomeSettlementLogList',
            component: () => import('@/views/operation/salary/guild-income-settlement-log-list.vue'),
            meta: {title: '工会结算流水'},
        },
        {
            path: 'salary/guild-payout-detail-list',
            name: 'GuildPayoutDetailList',
            component: () => import('@/views/operation/salary/guild-payout-detail-list.vue'),
            meta: {title: '工会代付详情'},
        },
        {
            path: 'salary/platform-anchor-payout-detail-list',
            name: 'PlatformAnchorPayoutDetailList',
            component: () => import('@/views/operation/salary/platform-anchor-payout-detail-list.vue'),
            meta: {title: '平台主播代付详情'},
        },
    ],
}
