server:
  ###系统配置
  address: 443  #http服务端口
  openapiPath: "/f9acdb1da4ed11ecc115d613e291af14-api.json" # OpenAPI接口文档地址
  swaggerPath: "/f9acdb1da4ed11ecc115d613e291af14-swagger"  # 内置SwaggerUI展示地址
  serverRoot: "/home/ec2-user/cdn"
  httpsCertPath: "/root/.acme.sh/www.bigtktool.shop_ecc/fullchain.pem"
  httpsKeyPath: "/root/.acme.sh/www.bigtktool.shop_ecc/privkey.pem"
  # PProf配置
  pprofEnabled: true # 是否开启PProf性能调试特性。默认为false
  pprofPattern: "/66dcd8e25ab3b339546ea1de5eb2d443e6fca76c76d11709f10533be8bd87d7d/pprof"    # 开启PProf时有效，表示PProf特性的页面访问路径，对当前Server绑定的所有域名有效
  ####自定义配置
  debugEnv: true #是否开启debug环境,不会检查权限
  exitTime: 5 #退出系统等待多少秒，开始发送kill -9
  dumpRouterMap: false
  # 多域名静态目录与HTTPS证书(SNI),详见 config/local/config.yaml 示例
  # 多域名静态目录与HTTPS证书(SNI), 不同域名指向不同静态目录
  # domainSites:
  #   - domain: "cms.bigtktool.shop"
   #    root: "/home/ec2-user/cdn/cms"
   #    certFile: "/root/.acme.sh/cms.bigtktool.shop_ecc/fullchain.pem"
    #   keyFile: "/root/.acme.sh/cms.bigtktool.shop_ecc/privkey.pem"


bufferSize:
  db:
    lazy:
      period: 15000 #懒缓冲池频率,15秒同步数据库
      small: 2000  #数据库更新数据缓冲-->对应sysdb->单行数据写入缓冲池 eg角色表
      middle: 15000 #数据库更新数据缓冲-->对应sysdb->多行数据写入缓冲池  eg背包表 邮件表
      large: 50000 #数据库更新数据缓冲-->对应sysdb->多行数据写入缓冲池 eg item_log表,
    fast:
      period: 30 #快速缓冲池频率,50毫秒同步数据库
      small: 20 #数据库更新数据缓冲-->对应sysdb->单行数据写入缓冲池 eg角色表
      middle: 150 #数据库更新数据缓冲-->对应sysdb->多行数据写入缓冲池 eg背包表 邮件表
      large: 500 #数据库更新数据缓冲-->对应sysdb->多行数据写入缓冲池 eg item_log表,邮件表
  websocket: #websocket缓冲池大小--个人玩家缓冲池
    size: 30 #推送缓冲池大小
    period: 100 #推送缓冲池频率
  goPool: #协程池大小
    size: 100


logger:
  path: "/home/ec2-user/log/"           # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log"         # 日志文件格式。默认为"{Y-m-d}.log"
  prefix: ""                    # 日志内容输出前缀。默认为空
  level: "all"                 # 日志输出级别
  timeFormat: "2006-01-02T15:04:05" # 自定义日志输出的时间格式，使用Golang标准的时间格式配置
  ctxKeys: [ ]                    # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
  header: true                  # 是否打印日志的头信息。默认true
  stdout: true                  # 日志是否同时输出到终端。默认true
  rotateBackupExpire: 0                     # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  rotateBackupCompress: 0                     # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
  rotateCheckInterval: "1h"                  # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时
  stdoutColorDisabled: false                 # 关闭终端的颜色打印。默认开启
  writerColorEnable: true                 # 日志文件是否带上颜色。默认false，表示不带颜色


database:
  logger:
    path: "/home/ec2-user/log/gf-app/sql"
    level: "all"
    stdout: true
  default:
    link: "mysql:root:Appledev882116@tcp(127.0.0.1:3306)/live_db"
    extra: "charset=utf8mb4&parseTime=True&loc=Local"
    debug: true