-- 在正式服执行: mariadb -h127.0.0.1 -P14501 -uroot -p < grant_live_user.sql
-- live 用户: 仅 live_db 库导入/导出权限

CREATE USER IF NOT EXISTS 'live'@'%' IDENTIFIED BY 'zp8JXc25eKK5wL4nnbhB';
CREATE USER IF NOT EXISTS 'live'@'localhost' IDENTIFIED BY 'zp8JXc25eKK5wL4nnbhB';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, LOCK TABLES,
  CREATE TEMPORARY TABLES, TRIGGER, REFERENCES, EXECUTE, SHOW VIEW
  ON `live_db`.* TO 'live'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, LOCK TABLES,
  CREATE TEMPORARY TABLES, TRIGGER, REFERENCES, EXECUTE, SHOW VIEW
  ON `live_db`.* TO 'live'@'localhost';

FLUSH PRIVILEGES;
